  const CDN = 'https://media.sellfy.store/images/lC8jT75D/';
  const CAMISETAS = [
    // ── TEMPORADA 25/26 · LA LIGA ──
    { id:1,  nombre:'FC Barcelona Edición Especial 25/26',           liga:'laliga',      categoria:['laliga'], imgs:[CDN+'wK7t/759c6a3b.jpg',CDN+'CRic/59ffa6d9.jpg',CDN+'ClWd/7df7440f.jpg',CDN+'5wxE/febacce0.jpg'],  tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo', orden:1 },
    { id:2,  nombre:'FC Barcelona Edición Especial 25/26 (II)',      liga:'laliga',      categoria:['laliga'], imgs:[CDN+'umVF/2a08b003.jpg',CDN+'NvnN/a016cce7.jpg',CDN+'BwN5/a995d1b6.jpg',CDN+'ui2T/51c96f12.jpg'],  tipo:'regular', badge:null },
    { id:3,  nombre:'FC Barcelona Edición Especial 25/26 (III)',     liga:'laliga',      categoria:['laliga'], imgs:[CDN+'FL5N/af8c6393.jpg',CDN+'QaX8/2e8e7106.jpg',CDN+'YEh5/8c092cd8.jpg',CDN+'ho7U/7a7f3bad.jpg'],  tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · PREMIER LEAGUE ──
    { id:4,  nombre:'Arsenal Primera Equipación 25/26',              liga:'premier',     categoria:['premier'],imgs:[CDN+'PNaK/ad869c5a.jpg',CDN+'7LyX/075242f7.jpg',CDN+'64FD/877cbffe.jpg'],  tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:5,  nombre:'Arsenal Edición Especial 25/26',                liga:'premier',     categoria:['premier'],imgs:[CDN+'vFc1/b4929dd3.jpg',CDN+'Tj6m/3a29760b.jpg',CDN+'rIRV/64ae545a.jpg',CDN+'1bEp/ad7a028a.jpg'],  tipo:'regular', badge:null },
    { id:6,  nombre:'Arsenal Edición Especial 25/26 (II)',           liga:'premier',     categoria:['premier'],imgs:[CDN+'zJ1m/8656f6ef.jpg',CDN+'pImE/f7064740.jpg',CDN+'OZ1q/357a5161.jpg',CDN+'Wrhd/bb5b80f2.jpg'],  tipo:'regular', badge:null },
    { id:7,  nombre:'Arsenal Edición Especial 25/26 (III)',          liga:'premier',     categoria:['premier'],imgs:[CDN+'zb6Q/a95664d8.jpg',CDN+'bxOB/9fa98423.jpg',CDN+'uQER/1a3034c3.jpg',CDN+'HLTv/006644fc.jpg'],  tipo:'regular', badge:null },
    { id:8,  nombre:'Liverpool Tercera Equipación 25/26',            liga:'premier',     categoria:['premier'],imgs:[CDN+'1jH9/9dcf060a.jpg',CDN+'WoCF/5e67f80c.jpg',CDN+'mcCO/c3e33179.jpg',CDN+'TbUJ/8868f1de.jpg'],  tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo', orden:2 },
    { id:9,  nombre:'Chelsea Tercera Equipación 25/26',              liga:'premier',     categoria:['premier'],imgs:[CDN+'OoNp/5cf25256.jpg',CDN+'LIcc/d9dd7582.jpg',CDN+'Yxa4/936cd6a4.jpg',CDN+'DUYp/bcf64b11.jpg'],  tipo:'regular', badge:null },
    { id:10, nombre:'Everton Tercera Equipación 25/26',              liga:'premier',     categoria:['premier'],            imgs:[CDN+'jx33/febe1c75.jpg',CDN+'PdY2/45cf8b68.jpg',CDN+'c621/2077bc73.jpg',CDN+'2QNe/e249345b.jpg'], tipo:'regular', badge:null },
    { id:11, nombre:'Fulham Primera Equipación 25/26',               liga:'premier',     categoria:['premier'],            imgs:[CDN+'vHuG/a3e049bb.jpg',CDN+'1Nac/a21eb010.jpg',CDN+'qdxu/90e1abc1.jpg',CDN+'tt1j/4f3877f7.jpg'], tipo:'regular', badge:null },
    { id:12, nombre:'Fulham Segunda Equipación 25/26',               liga:'premier',     categoria:['premier'],            imgs:[CDN+'TmKn/8e6e7520.jpg',CDN+'LO9y/f41684dd.jpg',CDN+'negc/3bc2e8c9.jpg',CDN+'PVCZ/7cddca6a.jpg'], tipo:'regular', badge:null },
    { id:13, nombre:'Fulham Tercera Equipación 25/26',               liga:'premier',     categoria:['premier'],            imgs:[CDN+'IBzT/8283501e.jpg',CDN+'Pyil/a1614ecd.jpg',CDN+'wOUO/f23d6230.jpg'], tipo:'regular', badge:null },
    { id:14, nombre:'Crystal Palace Segunda Equipación 25/26',       liga:'premier',     categoria:['premier'],            imgs:[CDN+'unjU/72f4c5e5.jpg',CDN+'wp6y/f1bc0240.jpg',CDN+'NcuY/505d6db1.jpg'], tipo:'regular', badge:null },
    { id:15, nombre:'Crystal Palace Tercera Equipación 25/26',       liga:'premier',     categoria:['premier'],            imgs:[CDN+'LXFf/60958f59.jpg',CDN+'Y0pU/a86c7a2b.jpg',CDN+'wwpK/b0b65ff2.jpg',CDN+'0rJb/6aad09fc.jpg'], tipo:'regular', badge:null },
    { id:16, nombre:'West Ham United Segunda Equipación 25/26',      liga:'premier',     categoria:['premier'],            imgs:[CDN+'zjQ1/80462317.jpg',CDN+'YWZc/191dc3ad.jpg',CDN+'RMCh/cee4cd34.jpg',CDN+'YBRJ/679bd272.jpg'], tipo:'regular', badge:null },
    { id:17, nombre:'Wolverhampton Primera Equipación 25/26',        liga:'premier',     categoria:['premier'],            imgs:[CDN+'Pg2x/e25c3fae.jpg',CDN+'aYpI/ece27259.jpg',CDN+'qKmO/fc2d071d.jpg',CDN+'DuHm/8d0b65d0.jpg'], tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · CHAMPIONS ──
    { id:18, nombre:'Bayern München Segunda Equipación 25/26',       liga:'bundesliga',  categoria:['bundesliga'],         imgs:[CDN+'Qce1/f72ddf89.jpg',CDN+'iRtt/620d00f2.jpg',CDN+'z7JK/05a3568a.jpg'], tipo:'regular', badge:null },
    { id:19, nombre:'Bayern München Edición Especial 25/26',         liga:'bundesliga',  categoria:['bundesliga'],         imgs:[CDN+'anDo/4a0ab168.jpg',CDN+'l2Mn/14b72647.jpg',CDN+'dQY9/4cd93dbf.jpg',CDN+'vP3x/5717197e.jpg'], tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo', orden:3 },
    { id:20, nombre:'Inter de Milán Segunda Equipación 25/26',       liga:'seriea',      categoria:['seriea'],             imgs:[CDN+'4g25/823d62cb.jpg',CDN+'KIAm/fafd0fa8.jpg',CDN+'rREI/1de89fa1.jpg'], tipo:'regular', badge:null },
    { id:21, nombre:'Inter de Milán Tercera Equipación 25/26',       liga:'seriea',      categoria:['seriea'],             imgs:[CDN+'HAHJ/3d1718cc.jpg',CDN+'O0HC/acd84b65.jpg',CDN+'46GG/569471bc.jpg',CDN+'yUDy/5b93208c.jpg'], tipo:'regular', badge:null },
    { id:22, nombre:'PSG Edición Especial 25/26',                    liga:'ligue1',      categoria:['ligue1'],             imgs:[CDN+'xfWz/c795a5a1.jpg',CDN+'MI6a/2d567fe0.jpg',CDN+'iRZy/7b3bceef.jpg'], tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo', orden:4 },
    { id:23, nombre:'Ajax Edición Especial 25/26',                   liga:'eredivisie',  categoria:['eredivisie'],         imgs:[CDN+'mmZB/66f31489.jpg',CDN+'B12A/e5ed9bd4.jpg',CDN+'bC0X/eb1751bf.jpg',CDN+'t0gH/45d4c938.jpg'], tipo:'regular', badge:null },
    { id:24, nombre:'Ajax Edición Especial 25/26 (II)',              liga:'eredivisie',  categoria:['eredivisie'],         imgs:[CDN+'mwtX/82779660.jpg',CDN+'Y09X/f2a49c7a.jpg',CDN+'zPVc/d80c07db.jpg'], tipo:'regular', badge:null },
    { id:25, nombre:'Ajax Edición Especial 25/26 (III)',             liga:'eredivisie',  categoria:['eredivisie'],         imgs:[CDN+'LXSJ/05b664e3.jpg'], tipo:'regular', badge:null },
    { id:26, nombre:'Ajax Segunda Equipación 25/26',                 liga:'eredivisie',  categoria:['eredivisie'],         imgs:[CDN+'fDmG/3c76a3c3.jpg',CDN+'MdZP/5a7cf913.jpg',CDN+'kbhZ/2277cd21.jpg',CDN+'AWKu/4f3877f7.jpg'], tipo:'regular', badge:null },
    { id:27, nombre:'AS Roma Segunda Equipación 25/26',              liga:'seriea',      categoria:['seriea'],             imgs:[CDN+'evBH/8d6f5a9b.jpg',CDN+'nGBI/0c86423f.jpg',CDN+'qx0p/a38cc48c.jpg',CDN+'pIaP/9aad3b3c.jpg'], tipo:'regular', badge:null },
    { id:28, nombre:'Bayer Leverkusen Segunda Equipación 25/26',     liga:'bundesliga',  categoria:['bundesliga'],         imgs:[CDN+'VNO2/9baa7282.jpg',CDN+'RZ0j/1134ce27.jpg'], tipo:'regular', badge:null },
    { id:29, nombre:'Galatasaray Primera Equipación 25/26',          liga:'superlig',    categoria:['superlig'],           imgs:[CDN+'QC39/3c629cc5.jpg',CDN+'Vtcw/d5670415.jpg',CDN+'60mC/57d54217.jpg',CDN+'KhxN/2f9daf53.jpg'], tipo:'regular', badge:null },
    { id:30, nombre:'Galatasaray Segunda Equipación 25/26',          liga:'superlig',    categoria:['superlig'],           imgs:[CDN+'5PXs/02637fe7.jpg'], tipo:'regular', badge:null },
    { id:31, nombre:'Napoli Tercera Equipación 25/26',               liga:'seriea',      categoria:['seriea'],             imgs:[CDN+'7z4k/75caf422.jpg',CDN+'qe3X/48486a69.jpg',CDN+'XIVM/21efda70.jpg',CDN+'4k68/3c27754a.jpg'], tipo:'regular', badge:null },
    { id:32, nombre:'Lille Primera Equipación 25/26',                liga:'ligue1',      categoria:['ligue1'],             imgs:[CDN+'eR2Y/503f1d7c.jpg',CDN+'ApiO/fc19fecd.jpg',CDN+'Vepd/8b2016e8.jpg',CDN+'R5nn/bda3823e.jpg'], tipo:'regular', badge:null },
    { id:33, nombre:'Lille Segunda Equipación 25/26',                liga:'ligue1',      categoria:['ligue1'],             imgs:[CDN+'4LMl/b1eb956f.jpg',CDN+'vnWo/47c07c62.jpg',CDN+'9D5d/3efd5554.jpg'], tipo:'regular', badge:null },
    { id:34, nombre:'Monaco Tercera Equipación 25/26',               liga:'ligue1',      categoria:['ligue1'],             imgs:[CDN+'J3pt/f8c7633c.jpg',CDN+'0bEV/019275f8.jpg',CDN+'YvuY/31c5f00d.jpg',CDN+'qTx5/6af00062.jpg'], tipo:'regular', badge:null },
    { id:35, nombre:'Marsella Tercera Equipación 25/26',             liga:'ligue1',      categoria:['ligue1'],             imgs:[CDN+'ODgk/f7f87fc4.jpg',CDN+'6rzM/704b2250.jpg',CDN+'g8AW/3bfc5b52.jpg',CDN+'V4pw/c341b93b.jpg'], tipo:'regular', badge:null },
    { id:36, nombre:'Sporting de Portugal Tercera Equipación 25/26', liga:'primeiraliga',categoria:['primeiraliga'],        imgs:[CDN+'wurg/bca0eb86.jpg',CDN+'XyzY/61d1de04.jpg',CDN+'t0UQ/d22d7fd5.jpg',CDN+'0332/33d2270b.jpg'], tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · SELECCIONES ──
    { id:37, nombre:'Italia Primera Equipación Mundial 2026',        liga:'selecciones', categoria:['selecciones'],        imgs:[CDN+'IE8f/607e7b45.jpg',CDN+'PdMI/cdc80e68.jpg',CDN+'h3X0/c9f55977.jpg',CDN+'LqJZ/ee2925b7.jpg'], tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo', orden:7 },
    { id:38, nombre:'Colombia Primera Equipación Mundial 2026',      liga:'selecciones', categoria:['selecciones'],        imgs:[CDN+'Qbxg/f0ae4fd1.jpg',CDN+'g49L/0339ed75.jpg',CDN+'3y44/9f6a45c6.jpg',CDN+'GDYB/5138bb0a.jpg'], tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:39, nombre:'México Primera Equipación Mundial 2026',        liga:'selecciones', categoria:['selecciones'],        imgs:[CDN+'BM12/076cf136.jpg',CDN+'EUbM/e4ea20f0.jpg',CDN+'euFU/78d63d2d.jpg',CDN+'dHXq/7b984258.jpg'], tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:40, nombre:'Marruecos Primera Equipación 2025',             liga:'selecciones', categoria:['selecciones'],        imgs:[CDN+'w5AT/6325674c.jpg',CDN+'bjQi/2ea2d170.jpg',CDN+'udGx/8127cedf.jpg',CDN+'vVNI/441f06da.jpg'], tipo:'regular', badge:null },
    { id:41, nombre:'Marruecos Segunda Equipación 2025',             liga:'selecciones', categoria:['selecciones'],        imgs:[CDN+'cGr7/bbd5a253.jpg',CDN+'O1jW/28e0416c.jpg',CDN+'0P2L/e9513628.jpg',CDN+'iozm/d81048f6.jpg'], tipo:'regular', badge:null },
    { id:42, nombre:'Portugal Segunda Equipación 2025',              liga:'selecciones', categoria:['selecciones'],        imgs:[CDN+'hTnx/31c7d7e1.jpg',CDN+'zEuO/4955826e.jpg',CDN+'F63d/56dc2e43.jpg',CDN+'f869/c144ab13.jpg'], tipo:'regular', badge:null },
    { id:43, nombre:'Portugal Prepartido 2025',                      liga:'selecciones', categoria:['selecciones'],        imgs:[CDN+'TpLb/a3f5d642.jpg',CDN+'rP9a/46ced123.jpg',CDN+'dH0g/c0e867e2.jpg',CDN+'MBVH/a0429c14.jpg'], tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · SAUDI PRO LEAGUE ──
    { id:44, nombre:'Al Hilal Tercera Equipación 25/26',             liga:'saudi',       categoria:['saudi'],              imgs:[CDN+'7fvJ/14d78e4b.jpg',CDN+'Ry4t/6546ea66.jpg',CDN+'7D2P/451aa957.jpg'], tipo:'regular', badge:null },
    { id:45, nombre:'Al Nassr Segunda Equipación 25/26',             liga:'saudi',       categoria:['saudi'],              imgs:[CDN+'VG7p/b55e6aa4.jpg',CDN+'UmYD/c7e0e5ee.jpg',CDN+'Ayia/8d7a31f3.jpg',CDN+'U4Rt/6149b6c5.jpg'], tipo:'regular', badge:null },
    { id:46, nombre:'Al Ittihad Segunda Equipación 25/26',           liga:'saudi',       categoria:['saudi'],              imgs:[CDN+'uSSV/152b8c35.jpg'], tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · OTROS ──
    { id:47, nombre:'Flamengo Tercera Equipación 25/26',             liga:'otros',       categoria:['otros'],              imgs:[CDN+'PyU9/555de64b.jpg',CDN+'8w02/f70b508e.jpg',CDN+'DFwy/bf083742.jpg',CDN+'JwYx/d4666ee1.jpg'], tipo:'regular', badge:null },
    // ════════════════════════════════════════════════════════
    // ── MUNDIAL 2026 ──
    // ════════════════════════════════════════════════════════
    { id:48, nombre:'Francia 1ª Equipación · Mundial 2026',        liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287451/7217f42f_sogxns.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287433/4b89b70a_plskxz.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287432/17b9403b_1_vgaw0s.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287432/b09ae299_ecr6tu.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:49, nombre:'Croacia 1ª Equipación · Mundial 2026',        liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287431/1150d5c7_pfujon.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287432/48d972ea_htr4nm.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287431/a75afbe1_xqzfyi.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287430/6d6273b6_aqwpgm.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:50, nombre:'Croacia 2ª Equipación · Mundial 2026',        liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287430/be015e7f_wzy9wh.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287430/470b7c3a_mlnfvd.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287449/3f4e8b3e_vahhck.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287428/8ad09789_sep4o4.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:51, nombre:'Marruecos 1ª Equipación · Mundial 2026',      liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287411/5d2f2b42_kttvgg.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287411/fcb8cef9_owdfoi.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287411/a8ad5267_dpryhv.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287410/07c84c92_sqgdwx.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:52, nombre:'Marruecos 2ª Equipación · Mundial 2026',      liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287428/87ce73f2_l5kq0t.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287427/e743d227_zcgzz7.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287427/8ed53fc5_yibwlf.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287427/8271ee98_xeqzxe.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:53, nombre:'Países Bajos 1ª Equipación · Mundial 2026',   liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287420/46e28df6_v6y584.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287420/551b3abf_fhfpgw.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287419/6358dd3f_teozlm.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287419/44256e95_v1n8qf.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:54, nombre:'Países Bajos 2ª Equipación · Mundial 2026',   liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287422/fa41476f_tbeduf.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287422/f87672b1_zrm7km.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287422/0ecd3792_hja22y.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287421/71bd1ad5_euvjz7.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:55, nombre:'Suecia 1ª Equipación · Mundial 2026',          liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287419/7549c709_j3aoq8.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287419/a2591127_wm9uwx.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287419/889d143d_wzu0yg.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287418/a4519364_mvnidy.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:56, nombre:'Turquía 1ª Equipación · Mundial 2026',         liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287426/b7e777b9_ieii9a.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287425/8db2f069_lwbmkv.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287425/e7613c76_blhyaa.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287424/a00059aa_mvvdsr.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:57, nombre:'Turquía 2ª Equipación · Mundial 2026',         liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287424/d4cbdcd3_eeog7l.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287424/dec4ce9b_pntgxa.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287423/ae11ec1f_kpepso.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287423/3b0773a5_aaew8l.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:58, nombre:'España 2ª Equipación · Mundial 2026',          liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287417/a7494a84_rxwnqn.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287416/595f8c7f_z0luom.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287416/b5885ea3_cqhmgl.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287415/d1ca21a7_bpbnui.jpg'],
      tipo:'regular', badge:'top', badgeTexto:'🔥 Más Vendida', orden:0 },
    { id:59, nombre:'Alemania 2ª Equipación · Mundial 2026',        liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287414/f97d8518_jhtgfb.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287414/e49f0d53_udprev.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287414/06cb476d_xfoqob.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287413/74a653e0_jjkubb.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:60, nombre:'Argentina 2ª Equipación · Mundial 2026',       liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287413/e8ad5285_gjdikv.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287412/ed83d678_d73qek.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287412/14e8ae81_d62hfl.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287412/51d73189_zseoeu.jpg'], orden:5,
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:61, nombre:'Inglaterra 2ª Equipación · Mundial 2026',      liga:'selecciones', categoria:['selecciones'],
      imgs:['https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287409/7a570a72_zv7zh1.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287409/70ad6a72_s9fxdy.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287408/c0805123_h5k6ku.jpg','https://res.cloudinary.com/dol4vb6ah/image/upload/v1779287408/042c4bfb_enw6vq.jpg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:62, nombre:'Argentina 1ª Equipación · Mundial 2026',      liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1kCwLHytfFntS0UrZ1t0eEh-c23On4QN_','https://lh3.googleusercontent.com/d/1yporQ9A4wlpQJGxxpBEPn0KG3ICoDo7l','https://lh3.googleusercontent.com/d/1Lk-4GMn10OpYGAD9OHe-6Q0_u3OC47k6','https://lh3.googleusercontent.com/d/1TunSFKfEaPUqYLwdl6a0d30d1YjPy8UK'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:63, nombre:'Brasil 1ª Equipación · Mundial 2026',         liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1LnP5174_2cjKjAXk0FxaSKpCXsew1NIf','https://lh3.googleusercontent.com/d/1-jwBvkDXwtmGVBzGFbxcE4_xvLBBW4Fr','https://lh3.googleusercontent.com/d/10hbQ-Ef47udicKYEkIiYMEhZ8LpjwOfU','https://lh3.googleusercontent.com/d/1EZHWBMqWHtj0MJGEZf-oVZJY7Unn_d2H'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:64, nombre:'Brasil 2ª Equipación · Mundial 2026',         liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1GGrZuVRM4Yqfw7rkb63ropo_Ug2hgWZW','https://lh3.googleusercontent.com/d/1qCfGg3HKZkhD1V-s_hUzMJSVUrtJnqr6','https://lh3.googleusercontent.com/d/1Nxh89BQwOE4xYwu76MKureiL570Qwi6l','https://lh3.googleusercontent.com/d/1JZZvXUfmEZPMSMFT5Jtr4KQbegOny4H0'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:65, nombre:'Colombia 2ª Equipación · Mundial 2026',       liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1pDXjL9nDx1aU1OJNcBuSHxr66nqsMr1n','https://lh3.googleusercontent.com/d/1xOZKTsAtkneCWogfyVWhPBsbLQcavSDN','https://lh3.googleusercontent.com/d/18xOxSXHs08e6ORmVJOGVhci39SFN0cFd','https://lh3.googleusercontent.com/d/1yRue62t8oIx9aczFDXUvJEuWvOaQCMrL'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:66, nombre:'Escocia 1ª Equipación · Mundial 2026',        liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/10SutmDg0KGLsUCvZwhgv12o55VIvxYqn','https://lh3.googleusercontent.com/d/1KOqVkMzPC86byl9MREmpujhPAsZpRWIt','https://lh3.googleusercontent.com/d/18GFTNPzc-n44Pe7o5OkgWKtvh-fii8mH','https://lh3.googleusercontent.com/d/1yGLdLURpmNQi05AJqw7PO30WGISgUMaZ'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:67, nombre:'España 1ª Equipación · Mundial 2026',         liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1TjPLbodfnJIlf5tQmWom54_kYqQ10P6i','https://lh3.googleusercontent.com/d/18e4ooGNzaseEwSoBca41g0JMVcrmQ6zF','https://lh3.googleusercontent.com/d/1M4syrVVghjLxEZD8AXS30bk9pmnGkBAf','https://lh3.googleusercontent.com/d/180uJIvgj51xh5SIRjgGSKW5TMUOLbVoL'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:68, nombre:'Estados Unidos 1ª Equipación · Mundial 2026', liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/19vdfqYL2A9nquZxwlSBr2vMCpZ20IGPR','https://lh3.googleusercontent.com/d/1JY18oHEOOn3A-VujFW5q8C5tHAw_Oec-','https://lh3.googleusercontent.com/d/1Q4AWb_0cOG6UDQ7nb543P1WFVgRkPH5e','https://lh3.googleusercontent.com/d/1Xa6q4nxyguFDVchuOdd-e3G33ywl2dxe'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:69, nombre:'Jamaica 1ª Equipación · Mundial 2026',        liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1OVB55IYmWXs-5cJv2yewOPZWBl8w2cL-','https://lh3.googleusercontent.com/d/1ruwr3V1Q_en5gYPF-xrYvzm9e_xu1HfB','https://lh3.googleusercontent.com/d/1IXdyPgPcV5AkdaFX-8HujRLKILzH4gby','https://lh3.googleusercontent.com/d/1AIeaxUXSuD8V8615tbswaJwvALSH_mFm'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:70, nombre:'Portugal 1ª Equipación · Mundial 2026',       liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1UOhVhKFQ_KYXBQ8TRXAfmAz-jRCo7fef','https://lh3.googleusercontent.com/d/1g1x3f7-dACUlkF6gDxeWiyB1uPxcrn8O','https://lh3.googleusercontent.com/d/1KOQzYoTwzaTtoV9ahDvpaujSeS8gT8Ms','https://lh3.googleusercontent.com/d/1ZjNaxAgR0zpPa6GPSX3EUu6c_xe7fGz2'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:71, nombre:'Portugal 2ª Equipación · Mundial 2026',       liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1mx4QA-xSZE3XkyDTg-d3lC324-D5VSzo','https://lh3.googleusercontent.com/d/1JkIPCrwH0z0j9uVRCMsBXyJqNDQnZyBr','https://lh3.googleusercontent.com/d/13CHV6fVwR9kbYBFFUdbaedP67CB2tU06','https://lh3.googleusercontent.com/d/1GT44J3YHrU23MnCKZPgLfXANmVmwFb7G'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:72, nombre:'Suiza 1ª Equipación · Mundial 2026',          liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1JFyHlt7Bs5fVspYch8onEV1PoCdGfl84','https://lh3.googleusercontent.com/d/1ga5FXTjO_ltzsh1PCPyBeuf-gZxNIVyW','https://lh3.googleusercontent.com/d/1NRAxEGNUCu5A3u2wzXzD1oCkmuOHI45m','https://lh3.googleusercontent.com/d/1vb1bKTWIQTZswtsxZZeG6RtwiFNwqKEx'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:73, nombre:'Uruguay 1ª Equipación · Mundial 2026',        liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1_fOD2ymwT35F5Gc95ITVqaTNX5s0x65m','https://lh3.googleusercontent.com/d/1tR_WSumkXORGUsH-DXAQvS5t9FVuZX6a','https://lh3.googleusercontent.com/d/1KekRQGUJE0-RU2BJ423IZO8ossN-aRSH','https://lh3.googleusercontent.com/d/1GboJt_14e0tOmjgnD2du7GAjKvqjtNfj'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:74, nombre:'Alemania 1ª Equipación · Mundial 2026',       liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1YfL5AO6nPHD-j6FXbvQTdkvyFQHXkHlM','https://lh3.googleusercontent.com/d/1izlBinOiEY8So3t_M_cxAmgC0Qp7nl5z','https://lh3.googleusercontent.com/d/1vlt6ztc6xRAxmlIk0tbFw1bGf6oVH3A-','https://lh3.googleusercontent.com/d/17HslAEouIQ6gQGnqGne5cUGFU8QmGLIK'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:75, nombre:'Inglaterra 1ª Equipación · Mundial 2026',     liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1aketuu1bX05ayZ4v_V8hpkVc2gAbHBBB','https://lh3.googleusercontent.com/d/1Bx7RYKHocZr5-BnVsJYZHPaqHgJHrbWG','https://lh3.googleusercontent.com/d/1Meo4qTfq3Trfcae0hlfjbUMaRr4AyPJS','https://lh3.googleusercontent.com/d/1-xLgO82R1RlNDcEoNfVQSNz4yFeWu3dk'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:76, nombre:'Bélgica 1ª Equipación · Mundial 2026',        liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/19QCi_8bfZk4i_4HOhV3-7Zgn_pMoY-uU','https://lh3.googleusercontent.com/d/15iXdy4LyUlI1ffGEtXV0ir_pJaODBeDr','https://lh3.googleusercontent.com/d/1BZGtWzXlC-yXMlYRVG5tLaP3e37c6_zb','https://lh3.googleusercontent.com/d/1nn8xMTcRMijIn1hD4OAQqXgFygWNWvGH'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:77, nombre:'Bélgica 2ª Equipación · Mundial 2026',        liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1BZAM_4h1HWTOhwhd84BuznSLveY1zVyo','https://lh3.googleusercontent.com/d/1F6R7RAdHT3deg7GevLoOdYVw1J5itjKK','https://lh3.googleusercontent.com/d/1zdHyrXRgIS8s1w79Fd_-7jixtIJ6_Nfc','https://lh3.googleusercontent.com/d/1Qwl0aQ7NRo988QQMCVAFqnqjD0rVdUFT'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:78, nombre:'Costa de Marfil 2ª Equipación · Mundial 2026',liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1M5N5O8FkEFh44xarCFKpPupqNE0kP1wH','https://lh3.googleusercontent.com/d/1mbpe1xKslQJp1waUDPuadBdjdvycEtQ2','https://lh3.googleusercontent.com/d/1RvSF-TCr_d7TJiq-WCYqVDp7rr9pfa2t','https://lh3.googleusercontent.com/d/1DFlMRO5-drnoyWc2h-cdKUdea4M2omJ_'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    // ════════════════════════════════════════════════════════
    // ── TEMPORADA 26/27 ──
    // ════════════════════════════════════════════════════════
    { id:79,  nombre:'FC Barcelona 1ª Equipación 26/27',       liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1fGADT6GiHsfGzOOeTemmWjEhtT9ftUdf','https://lh3.googleusercontent.com/d/1NbmUVzmngM3cOLQFMSK09w0KnIIhCwVd','https://lh3.googleusercontent.com/d/18ZVHYALT-QIehCo2tbRT5BTGikMSiVd0','https://lh3.googleusercontent.com/d/1t_CxAmquraiRaU82sbqy9IDrnXa371y3'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:80,  nombre:'Real Madrid 1ª Equipación 26/27',        liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1djFSE2vojA_8wsQM1OVk1m8_3LMrUHS-','https://lh3.googleusercontent.com/d/1BZ8YoQy-029P_OR1xcVhWJ0Fh1SiohqM','https://lh3.googleusercontent.com/d/1Oa5f792XD2IKwD7p038tzKfERD-BNxtW','https://lh3.googleusercontent.com/d/1TtnciYPUMCjHVkbywqODXVnGaUE7il3Q'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:81,  nombre:'FC Barcelona 2ª Equipación 26/27',       liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1tH_XhTBqww39UnZJT8JzyyE83gQAz9kp','https://lh3.googleusercontent.com/d/18w3IjhUBMrbFWn06K510zJ48Tr5iEDmN','https://lh3.googleusercontent.com/d/1lx_STwBv3TO9vpFNwYARKIu_SQvPbJvg','https://lh3.googleusercontent.com/d/15h1DQbZGf_Rg5NuKDCxtIquWE20l1dnU'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:82,  nombre:'Real Madrid 2ª Equipación 26/27',        liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1w_7Lh72KDgVIFQVa1sCiy-5vdL05MtLd','https://lh3.googleusercontent.com/d/1IkSMYNLxKNb6bjj-1lIso6o8vuCO83am','https://lh3.googleusercontent.com/d/1VWbskDQOgeEPanWtB0ylxqeODnc7kLwv','https://lh3.googleusercontent.com/d/1Fg08Ga9gNuKzK-GS5FPgKPiYyVhf0mPZ'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:83,  nombre:'FC Barcelona 3ª Equipación 26/27',       liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1UGtSPYRWSqy44S_30suv68Hrblz15cNY','https://lh3.googleusercontent.com/d/1cQMj30P4W32KeF4ompS51wOkSZsM57zn','https://lh3.googleusercontent.com/d/1Vszczxc9-cZ2HyK1TbGTVjVmYKIzA8_8','https://lh3.googleusercontent.com/d/1mrtsPQ6iHzbOm_TAKcUI3hM7EbSpEiQb'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:84,  nombre:'Real Madrid 3ª Equipación 26/27',        liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1wrlWKnr-8HzmrezAzos8EIzYnmKykjx1','https://lh3.googleusercontent.com/d/1N3Vnv8earnDke_JI25w3juhssCI7qiQK','https://lh3.googleusercontent.com/d/1ctC6F_j1EQFRZjj36vA1vsJRJhjoXyzi','https://lh3.googleusercontent.com/d/1Cb5gTmJbroEhmLv_mqlTHnzEaLcICeBu'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:85,  nombre:'Arsenal 1ª Equipación 26/27',            liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1hCjO1tzV1NOJ_G8P0it8H9gANElPd2_f','https://lh3.googleusercontent.com/d/1REQi5R4G9H5Skb9p-eS5g7u77KETTDi-','https://lh3.googleusercontent.com/d/15H2mJ4lWJ8KuKTBjLFd6FSV44hRW9cN-','https://lh3.googleusercontent.com/d/18tpuLl_63Hm1C15uCO73Pl5uaiiUCrhA'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:86,  nombre:'Aston Villa 1ª Equipación 26/27',        liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/18Y7qA2qtulO4cNPj-XCpdYZd6FrAMj5p','https://lh3.googleusercontent.com/d/1YI-iuUFzwuhOTWnCmmF6zteyMO1945RB','https://lh3.googleusercontent.com/d/1glVoK3IJjKLneDXgXKKe0wiVUmhTc8Zc','https://lh3.googleusercontent.com/d/1O4HRScIcCEg2lPr51oVJXHrlZRzihbcF'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:87,  nombre:'Chelsea 1ª Equipación 26/27',            liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1u0oFYepyoIHuAhgKbS-RxVXx5lx7o0PH','https://lh3.googleusercontent.com/d/1SM0tWXYtTMdbhzLCSZUkWnMCK2bjGe2u','https://lh3.googleusercontent.com/d/18SSVUdRlv-c8coRHraLLCzFPQf4GOLRH','https://lh3.googleusercontent.com/d/1OBNb-FRzkiCAyW4CtZ3IK1EwIj9mVTdw'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:88,  nombre:'Liverpool 1ª Equipación 26/27',          liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1Q98MbKom1bCJet3UFdygEDF9FbYIdsdp','https://lh3.googleusercontent.com/d/11M2iIpg1HNV6gyUHr5MJWy3WmhuQRjk2','https://lh3.googleusercontent.com/d/1jWgU-Aw4mOgxGNoWMvuiJHaTMJK2YFPQ','https://lh3.googleusercontent.com/d/1kzq1X2yKH4vtP-cDP_QSMeEJAyfWdmsO'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:89,  nombre:'Manchester City 1ª Equipación 26/27',    liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/15hptBBGiGKKzGMjzMqizFu5MnuX6Tsp7','https://lh3.googleusercontent.com/d/1TFmgJUgELvyXYRZYFOTqVO7Vo5IlIUQ-','https://lh3.googleusercontent.com/d/1h_PF3zjMp_iqM_OYqpQG_Y0juQqXGKsO','https://lh3.googleusercontent.com/d/1gXw7DPd64n7N1AFnIuIRl5LHxhkObikF'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:90,  nombre:'Manchester United 1ª Equipación 26/27',  liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1jg83L8ehttN15EEtGz5WzsVRyUBgziSO','https://lh3.googleusercontent.com/d/1LX3Te7Z4d1CB1xZJUyfxeYvVN_bdKM9-','https://lh3.googleusercontent.com/d/1HmbGplEmF1eE-Z7aftgH7VsSOVDkRQXU','https://lh3.googleusercontent.com/d/1rRzWWuP_3QjbouZLeW_9UuqIWbGsFKt7'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:91,  nombre:'Arsenal 2ª Equipación 26/27',            liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1PgcsBmvVQdBS3OYxm4O3WA6tWDmA3zDr','https://lh3.googleusercontent.com/d/1ggPYlzj3tM0o-WUIQEnEU5hBlrZOOvLz','https://lh3.googleusercontent.com/d/1RsoTlAiVkQQBKgy0B4ZnbiyAL_EpSv6i','https://lh3.googleusercontent.com/d/1POHVhDgkd_js5GxqWK0-LEM8xOXt4f_e'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:92,  nombre:'Chelsea 2ª Equipación 26/27',            liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/10IDYEUZOk9nh_NbLMi8J0f8PuSYlEGRX','https://lh3.googleusercontent.com/d/16zBueTmDQlhfBE2OmKxMq_fmSBz4KMrk','https://lh3.googleusercontent.com/d/1rwRPqPHNwUzg1RhgoG6_oSA5Xly-ntAK','https://lh3.googleusercontent.com/d/1K0y_YEL0OC0yzHJ0kAGHMpFC_AL9TVRh'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:93,  nombre:'Liverpool 2ª Equipación 26/27',          liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1HsM7pxojvfuD4qg7ynLvpHmcC2565V_4','https://lh3.googleusercontent.com/d/1oJocdNM8-BmNzGUJ4LE1fGdwYeBdZvnv','https://lh3.googleusercontent.com/d/15yrbDK4nOJ1NXEbvJipLA9qOAeiOV6IW','https://lh3.googleusercontent.com/d/1Mp6dCbGBef4dZzxqbHuxMRRFcpvJW58c'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:94,  nombre:'Manchester City 2ª Equipación 26/27',    liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1PWu8Kk-y4RVp9y180RfixraUhWuLOWFn','https://lh3.googleusercontent.com/d/1XUixAnRBX5MXxelURGJLiB3rVx2FeXY_','https://lh3.googleusercontent.com/d/19wsTgoC3ce8p5i9E88sv8rftIwQxSN6-','https://lh3.googleusercontent.com/d/1MaWG_OyH3ENRXJ8QUYN5wP2rG0FLEH0J'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:95,  nombre:'Manchester United 2ª Equipación 26/27',  liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1RYnguKs_Smk-3gxdByQ_hpR47CZmZZy1','https://lh3.googleusercontent.com/d/1FTN_32AdderBKKmDSmji7ps2G355DN2z','https://lh3.googleusercontent.com/d/1rXzWSHPFUf-DHt1Geq_zGgD6F2rKQyMC','https://lh3.googleusercontent.com/d/1ExYSC8oMB2zMWsGCHiEs8qXiptpKnexx'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:96,  nombre:'Arsenal 3ª Equipación 26/27',            liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1egqR_vakoCkeAabjNc2oYBjY3_1tfIdg','https://lh3.googleusercontent.com/d/1_PfbmLKPbQCTAxFM5gePG0JtBFHkDx0F','https://lh3.googleusercontent.com/d/1Q32AUQFL7QqKtyacSYpd1_6GGL_eavKL','https://lh3.googleusercontent.com/d/1r_e0z189r7JL4fvfSdpa7q4a4DZNbM__'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:97,  nombre:'Manchester City 3ª Equipación 26/27',    liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1WzVZ0wxU3aD2BMywWdyUPzm_xxAhIjQT','https://lh3.googleusercontent.com/d/1xNBHSIgCTZ7jyqw-8bBeZ1scyJ3EfIFC','https://lh3.googleusercontent.com/d/1lCVKKCgprSu-uzTM8m_40FxeaEovdhrl','https://lh3.googleusercontent.com/d/17qQmmoPptEOWBqwyppG914TJjUwAK1Hz'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:98,  nombre:'Manchester United 3ª Equipación 26/27',  liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1zlJjSkWoSkZzHNM5kZnPUkoEIbeLLCp2','https://lh3.googleusercontent.com/d/1rQBgrptr8eayJ-0hzhW4lYAWDaZ9fB_Q','https://lh3.googleusercontent.com/d/1JzANbC6I5nVCZq6XRlT9hZn9Nd67GLB5','https://lh3.googleusercontent.com/d/1aJ7jpvKPRUU36VWYlC71XuAeyP9tNtLt'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:99,  nombre:'AC Milan 1ª Equipación 26/27',           liga:'otros',   categoria:['otros'],
      imgs:['https://lh3.googleusercontent.com/d/1oDnhI0Rrig7S4sG80ZMcd8YPFyokqcPE','https://lh3.googleusercontent.com/d/1DgN4S53vFaAf63rhKbLvymNyif9mM19V','https://lh3.googleusercontent.com/d/1jP8U15P0XTalU_JMuSg9Gkn4mFPrWMVi','https://lh3.googleusercontent.com/d/1pLbk2V2y2NDyM8Jw29TcnTBsCuP0dFD0'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:100, nombre:'Inter de Milán 1ª Equipación 26/27',    liga:'otros',   categoria:['otros'],
      imgs:['https://lh3.googleusercontent.com/d/1MLxsfUFeZhZRBXK2qM4i80x3KhaTKars','https://lh3.googleusercontent.com/d/1-uefGUsVroTIHuI7FvYXj3d6NJpoJTuj','https://lh3.googleusercontent.com/d/1sKnGcDSTf6xRZWIxyiHNIBaAvss1iMyG','https://lh3.googleusercontent.com/d/1oORIEtNQk6fUtIYSBpNT1QjTNjMEXcvw'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:200, nombre:'AC Milan 2ª Equipación 26/27',           liga:'otros',   categoria:['otros'],
      imgs:['https://lh3.googleusercontent.com/d/1MSrcMh6GfIe5tNn3rmZ3NZ17vnK-Qgq0','https://lh3.googleusercontent.com/d/19lCiMClXF-2eqFOavtr1pH4NGS4D-ANG','https://lh3.googleusercontent.com/d/1G90l1TTu74Fqf2JErXzYR5IzTUSRy1iy','https://lh3.googleusercontent.com/d/1EQvvwN00MPjYn7XJQ_51P97xCi5i_LXg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:201, nombre:'Bayern München 1ª Equipación 26/27',          liga:'bundesliga', categoria:['bundesliga'],
      imgs:['https://lh3.googleusercontent.com/d/1C5iHRkm3Thntvmf4mV68nD_XPh353BVq','https://lh3.googleusercontent.com/d/1Pk_dKyfP4vAclpl8HC0CYQkilTE02hZs','https://lh3.googleusercontent.com/d/1B4OCbIPaxsYNyfrN-tSnWZ-0Ljb9vm6L','https://lh3.googleusercontent.com/d/1pvu7cQtCSzRgrwCTzyazp9SHO0jzTNsl'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:202, nombre:'Bayern München 2ª Equipación 26/27',          liga:'bundesliga', categoria:['bundesliga'],
      imgs:['https://lh3.googleusercontent.com/d/13VrdzUXjCfBHx6mLLUAcYB9QVSgenH73','https://lh3.googleusercontent.com/d/1ng_PowMJpHTa6v5Pm0rngZAYKZlnILag','https://lh3.googleusercontent.com/d/1c9lHn4GZGIc8le9kcPpZhFHJF2V9HunB','https://lh3.googleusercontent.com/d/1tdiP5WEXJFP2BV-BaAKAOQdR-nUvIrop'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:203, nombre:'Olympique Lyon 1ª Equipación 26/27',          liga:'ligue1',  categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/1pb3ErFocG8DHecXsbYJD13PRUw3pInkW','https://lh3.googleusercontent.com/d/1jsl90bT6K8coeo-xo3bYVXeONZmNgg9P','https://lh3.googleusercontent.com/d/1AzluS_QM_qS5f5eKEST-whLFPENCeY9F','https://lh3.googleusercontent.com/d/1L-U0AshnewKDq87LyoQOPHbZnHDiQQ1Y'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:204, nombre:'PSG 2ª Equipación 26/27',                     liga:'ligue1',  categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/13X1N7-NhjYiWYBL1YEx37eO-P9tUGyk2','https://lh3.googleusercontent.com/d/1BoHRXOgcTB7QUEJdHqqWjsVM3lU3qMzB','https://lh3.googleusercontent.com/d/1pL-kt76d4gCK-sD-OBO4fRd3T47dp3JN','https://lh3.googleusercontent.com/d/1LzWxioJ_6-DkQuYpS-k5ihXO03vOf0d4'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:205, nombre:'PSG Pre-Partido 26/27',                       liga:'ligue1',  categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/1NLLkkKHJzO0rLHNG6Mtw-1AUveoNI1ym','https://lh3.googleusercontent.com/d/1baV6EUsnsjPweznKd0huxt91NsTK38Va','https://lh3.googleusercontent.com/d/1RHKrG54t_s9K52FgcMCDLEisXDeXIsHg','https://lh3.googleusercontent.com/d/1-a4qfnwSqBib-wcGFGdZcDK06WJrGpA2'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:206, nombre:'Ajax 1ª Equipación 26/27',                    liga:'eredivisie', categoria:['eredivisie'],
      imgs:['https://lh3.googleusercontent.com/d/1TIgqUoy8sKUzOgwhDUHjXkCOEiMMp4a0','https://lh3.googleusercontent.com/d/1FsrRUd15ZlDHdOCh4fEXs6bNQj2mzVeI','https://lh3.googleusercontent.com/d/1k5cgPrYmkDnTrrYz_jjHXuEErfiYL7Nx','https://lh3.googleusercontent.com/d/1ySqLKwsgLsPgcMMzOIclKUsBSlX26aRa'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:207, nombre:'Ajax 3ª Equipación 26/27',                    liga:'eredivisie', categoria:['eredivisie'],
      imgs:['https://lh3.googleusercontent.com/d/1Nq7kVZvUHQHmQsjeLoQ4oiQ8cqFjJ5e2','https://lh3.googleusercontent.com/d/14er9LGnBPyfv_D9fZevQ0sxbCXgI_rms','https://lh3.googleusercontent.com/d/1dEajANZ1Q7DaNtz7ZwJYb58orAlPTRmI','https://lh3.googleusercontent.com/d/1SsPsytQUbriq71BJZRJXKCEKpGdD-hnH'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:208, nombre:'FC Oporto 1ª Equipación 26/27',               liga:'primeiraliga', categoria:['primeiraliga'],
      imgs:['https://lh3.googleusercontent.com/d/1O2nUTZXyZCCoG_pM0l5gZ1pAY8qo--em','https://lh3.googleusercontent.com/d/1kjKTV8hKebsCfzfFTi4Ky6HFNNUAYx5C','https://lh3.googleusercontent.com/d/1FLxtEv9_oFmzxgsAxybrckN6a5S9zWa-','https://lh3.googleusercontent.com/d/1DUwhZ4MwfqP7S4NaA2AX4VKzhoBd-hsB'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:209, nombre:'AS Roma 2ª Equipación 26/27',                 liga:'seriea',  categoria:['seriea'],
      imgs:['https://lh3.googleusercontent.com/d/1sJ9InOqB2_yvEahtXCHEKDhzgVLggUKt','https://lh3.googleusercontent.com/d/1VNd8dm346WtLpMw1Inapj2C4j0H44baM','https://lh3.googleusercontent.com/d/18VV3OI-E2FViCUlufDzULEnH2QBnL3Ws','https://lh3.googleusercontent.com/d/1CWA4BtVhTUGuqgDIVZIJW5TP4_F4sgNb'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:210, nombre:'Al Nassr 3ª Equipación 26/27',                liga:'saudi',   categoria:['saudi'],
      imgs:['https://lh3.googleusercontent.com/d/1e2yxxZZl5essywLCWMDXVDX1nlg3JuCR','https://lh3.googleusercontent.com/d/1lzPK28c8c-APZV9vhdpOaL36dmhAV4Mq','https://lh3.googleusercontent.com/d/1BLW5sOrOovFGOUHbVujt6-Yj9kA_08kn','https://lh3.googleusercontent.com/d/1oHhXB7NUlkoVkoS3Kzy0gDAszeeg05ki'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:211, nombre:'Newcastle United 1ª Equipación 26/27',       liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1EghvNyO8QiQyXL_e9EdQ_mVumsUyyb98','https://lh3.googleusercontent.com/d/1j1OEornFEWgyeNgvnvpSvFTeHeCUcNsl','https://lh3.googleusercontent.com/d/1gVkXI_V8s676eKqvKk7ewJeTblATt_Zl','https://lh3.googleusercontent.com/d/1LLMknjednJEhy6Y30_JSkVFeuqMMpDsg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:212, nombre:'Tottenham Hotspur 1ª Equipación 26/27',      liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1BmH0PNJoHc8p-GLQPhR8dVAv7ec-2UmL','https://lh3.googleusercontent.com/d/1dUOlSeHZTqr1x-x9mkUthIk2m7KBYMma','https://lh3.googleusercontent.com/d/1tEViTI_spl6RsvZS8IsI1b_DLvXmto5V','https://lh3.googleusercontent.com/d/1gC7NJONz7-d9J2tKM6NYJn3wtjr7U1vR'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:213, nombre:'Chelsea Edición Especial 26/27',              liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1dBZWjpyBU9ifkvL9X55FQPHk-jK0KVxW','https://lh3.googleusercontent.com/d/1xwe6U_ZHE21aGPSkgTRQUHsvin83f_RD','https://lh3.googleusercontent.com/d/1h0kpqb3zkWX7BrzEaOPYAbhEaL7wVvHm','https://lh3.googleusercontent.com/d/1reDT1aAEY_G5HguIM3KH8GrPPewBZB7O'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:214, nombre:'Liverpool Edición Especial 26/27',            liga:'premier', categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/147VdFUNqG55vIDbb_l9uNfIsAWvJtHr9','https://lh3.googleusercontent.com/d/1t5vCtBK2tF5tknroqemKciAhvnea0R71','https://lh3.googleusercontent.com/d/1hLJgu2JKFgnLxpamFdUAnwQyoqKN1Fko','https://lh3.googleusercontent.com/d/1Ua46MfX8oCLZXixORo_cKF187T51CU45'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:215, nombre:'Real Betis 1ª Equipación 26/27',             liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1yGKiKMRnLfEs6R6ixKpZTa-C0FX_p2Gc','https://lh3.googleusercontent.com/d/1_ZNAJaqHDjByZBiWdlkS-9ckYthxE_7R','https://lh3.googleusercontent.com/d/1WMNNDQkwBKVXhU9P0bY8W2awS7CL4HQb','https://lh3.googleusercontent.com/d/1spoAtqJtsQu_nRqITRYdTRtF0IYXkorN'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:216, nombre:'Atlético de Madrid 2ª Equipación 26/27',     liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/17_eFQZQ2Y_gTf6tpvXXU_lS9W86MzJWw','https://lh3.googleusercontent.com/d/1L5oLZTraiaEgHRs_t4fJkIpOW02zbM2Z','https://lh3.googleusercontent.com/d/145hFbWWQKlP5JiICAI6R0X5ded53aMQa','https://lh3.googleusercontent.com/d/18qOhMv8x3uXEGTbswI1w1iCUfEtKt5Nz'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:222, nombre:'Atlético de Madrid 1ª Equipación 26/27',     liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1vmqpWi0wq69W6nt1bneLMJIlur7oha54','https://lh3.googleusercontent.com/d/1ZGMEGYB4-4pWpmxhgpIttsE5c2JCcKjJ','https://lh3.googleusercontent.com/d/1-PbA9GoR6uV3klYAl5D9BjqMtRahQL9H','https://lh3.googleusercontent.com/d/1ZAXZ051bl2JKxfNO-TqMWsVWNAAyy1Vi'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:217, nombre:'FC Barcelona Edición Especial 26/27',        liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1XS3t6F17w_ZzHJIJUBYIcNrMjNlkM9Y_','https://lh3.googleusercontent.com/d/1_ApCFFHS8L6RvkAk0Qlra3wIs92f3GaJ','https://lh3.googleusercontent.com/d/1fxLOfIzmee6VD7kDvuNLjKNLLfvspOof','https://lh3.googleusercontent.com/d/1mznRUrpyuJ1PUI9HNTKgu71XOc2h95Tc'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:218, nombre:'FC Barcelona Pre-Partido 26/27',             liga:'laliga',  categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1jUfMj9Udrd-FAUB7YoP4XSJkDOaC5M0k','https://lh3.googleusercontent.com/d/1lLEZuPuq_m-j3F9xdNYRfeH62h8nykCo','https://lh3.googleusercontent.com/d/1V8pyz1keZxpFDapx2Sfid6Ou-UiJTwn4','https://lh3.googleusercontent.com/d/1G20BfgGq3VyLhHg-c4y570H4RSopDF1p'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:219, nombre:'España 1ª Equipación ★★ Mundial 2026',      liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/1kEjBeJOnJPoAro_IR4BAVLS8R58Rco8E','https://lh3.googleusercontent.com/d/1YPUxTpAY9vHx1kDxtHQ8dL-HKOwG9fTr','https://lh3.googleusercontent.com/d/1DYiu01BGyKn0dDmJlXBm5QyN6SUtjBXI'],
      tipo:'regular', badge:'campeon', badgeTexto:'★★ Campeones', orden:-2 },
    { id:220, nombre:'España 2ª Equipación ★★ Mundial 2026',      liga:'selecciones', categoria:['selecciones'],
      imgs:['https://lh3.googleusercontent.com/d/175VefWF0EvVmG_PjoM8hAfufP3RfjG1-','https://lh3.googleusercontent.com/d/1G8PU1Pwf9NhiosOVg1pK_k2nZWuTa5J_','https://lh3.googleusercontent.com/d/11L5vRyZFos-15tSd-HgyjgRwb5Fmh4PR'],
      tipo:'regular', badge:'campeon', badgeTexto:'★★ Campeones', orden:-1 },
    // ── LA LIGA nuevas 26/27 ──
    { id:223, nombre:'Valencia CF 1ª Equipación 26/27',                liga:'laliga',      categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1KvLEqcckdoGwSxpLy_mYvh9F8WMxoYOu','https://lh3.googleusercontent.com/d/1SSWEMvuUV15MWQzITuFbysQWooMbTRMD','https://lh3.googleusercontent.com/d/1da-47BhvgPKpPt2KLaWVRNO1bXD7FB-w','https://lh3.googleusercontent.com/d/1PEUjWxMsOfEo3XvfekQLL2n9fAfahgli'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:224, nombre:'Athletic Club 1ª Equipación 26/27',              liga:'laliga',      categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/17Zo-JOChVEJUkkcLsnArNxFpc01kLhKn','https://lh3.googleusercontent.com/d/1UgsltE4jClxWL7LNTcKhA05PJNbGqQMr','https://lh3.googleusercontent.com/d/1h_UlivsfZxjBIC8HLyw8Oi2K0Lvn--lC','https://lh3.googleusercontent.com/d/15KICbj5X4zi7h_Jb-pBOFGFY_xSStquF'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:225, nombre:'Real Madrid Equipación Entrenamiento 26/27',      liga:'laliga',      categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1WbYHXjmsqQtDGccdvBDVCwW8tYFJcANo','https://lh3.googleusercontent.com/d/1eIJBUr9OWc8C6HWx4oUEBLzkm8uYH737','https://lh3.googleusercontent.com/d/1ZVzPViMwWS2tI2hZaJbSHDtUDxIKbMQf','https://lh3.googleusercontent.com/d/1VkZPm99Xflobs7YTnj6KxnF9yjbu_5Wg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:226, nombre:'Real Madrid Equipación Entrenamiento II 26/27',   liga:'laliga',      categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1SsY-9Kx8XeAI6XJa6L1WyaKutcxpO3F0','https://lh3.googleusercontent.com/d/1khY6irbZIZXMi_vLLDy75AZz98a1kL9J','https://lh3.googleusercontent.com/d/1GKOy4vIx7B6z0jL_ZkpC_xt_ZQMV2Ceb','https://lh3.googleusercontent.com/d/1F8Dk9_t5XA-JmKGRM0mp0LQb7ClQkQuP'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:227, nombre:'Real Madrid Equipación Entrenamiento III 26/27',  liga:'laliga',      categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1Y_b4PxnKOFeaAfjJWQUG6jri9vvJfwAl','https://lh3.googleusercontent.com/d/1CkvfM74HS2kg3OYQg3q56DA-XmKz8Mve','https://lh3.googleusercontent.com/d/1gX3Gr168B8SDcUj0ae9MOm13DQetG1_e'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:228, nombre:'Real Betis 2ª Equipación 26/27',                  liga:'laliga',      categoria:['laliga'],
      imgs:['https://lh3.googleusercontent.com/d/1F9tmjO8Fy0DkVp9FBpulEdsXbfUQOnrb','https://lh3.googleusercontent.com/d/1C9DQiv5A_csPzJ8KANP6Ez_NBDHsXgWE','https://lh3.googleusercontent.com/d/19lkBsPFWGrD4MhwC4ZY3vRMdIHRJk-F3','https://lh3.googleusercontent.com/d/1CIGTK6VuWpq4eWea39yCosxtoC_3tp2a'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    // ── PREMIER LEAGUE nuevas 26/27 ──
    { id:229, nombre:'Everton 2ª Equipación 26/27',                     liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1BY0DQW7aT3XYJqjbfeTWzYEEcQqFseGF','https://lh3.googleusercontent.com/d/174IuLGONU1tsN5Kbi6IgD6k1fnuFYiDL','https://lh3.googleusercontent.com/d/19sbGO01caEfTPrnhC9mx1vxmVFsCy8X7','https://lh3.googleusercontent.com/d/1GvyrG9hghM1vvXZovDH5EZMH46xmxZwk'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:230, nombre:'Aston Villa 3ª Equipación 26/27',                 liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1X-X-N6pb3eqwPCoTRQwnB2I4KjZ_7QGx','https://lh3.googleusercontent.com/d/1hj62A0RUkQhCPNfz7FvgXtI3fPOCFzh7','https://lh3.googleusercontent.com/d/1-atWxzKI2wwXxXQ_G3GsODnMXTA3KiSz','https://lh3.googleusercontent.com/d/1ZUxq1GneeyAX8BixpRhR6Dh4JDYwoWZF'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:231, nombre:'Leeds United 1ª Equipación 26/27',                liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1KBlA6PBeo_yFlneh-K8WZ_p14DG9djdg','https://lh3.googleusercontent.com/d/1zDOcWoVMrS82oeKNMYvHRbOGk_D8kMSg','https://lh3.googleusercontent.com/d/1SHCufJgG0nx6YxeoK_AQBmBcBXBcQNVq','https://lh3.googleusercontent.com/d/1o_h7X_t3ZyCLEWGOBHOEFUdZ6_48fgjn'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:232, nombre:'Manchester United Edición Especial 26/27',        liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1Ef3aF_xZ3jE8HWLKEZiitJrD1TDvrFsA','https://lh3.googleusercontent.com/d/1WwrHHfutItv82TFyamoSfmQ6LDgKEIoj','https://lh3.googleusercontent.com/d/1UCuSl81Bt0QcejIVlwvhoLK0z7w4fxkl','https://lh3.googleusercontent.com/d/1Sc3mCfd2WhRIzQ63T7MY1I3VzF0xu3tL'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:233, nombre:'Newcastle United 2ª Equipación 26/27',            liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/111QFvH6pvXZ8OHlyimrKIS7OnfG0NGXQ','https://lh3.googleusercontent.com/d/1XnuzXKhB3dRdNuHcWQw6bOH6b5hLMaRg','https://lh3.googleusercontent.com/d/1Hd35eD0t_WVg5Wv0ZyMfVSksVUKMhNQa','https://lh3.googleusercontent.com/d/155M79qyx-0aMbDnaoRrxFpqRAHRBgBp_'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:234, nombre:'Newcastle United 3ª Equipación 26/27',            liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1dyBMiiS79BB4GC-GDvNRBNnpBKY5R2n1','https://lh3.googleusercontent.com/d/19IbtjUt1OgyctywKmpj28uOoKIruc2xN','https://lh3.googleusercontent.com/d/16kNFryUtj8KLCZ-YhUoilc9Kbs_c4Phi','https://lh3.googleusercontent.com/d/1dAB76qx7Kmy1jHFIa1R3hpu3H0sCzdeO'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:235, nombre:'Aston Villa 2ª Equipación 26/27',                 liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1dlGjvyoQgHh3ri8nLLwAXWfPT5BgraT4','https://lh3.googleusercontent.com/d/1f0CChTsYe_RU8YY-wbshC8NFeUqMspSc','https://lh3.googleusercontent.com/d/1hY87RpqmRiKr8k0WUkiVyhTf_2QiQedo','https://lh3.googleusercontent.com/d/1CWhoufOqx-o8BCbeix6xKmLabvGfK2Jy'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:236, nombre:'West Ham United 3ª Equipación 26/27',             liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1ZoMiPSKdcKqxm2t7rMkPynnMXDbMTfWD','https://lh3.googleusercontent.com/d/10of1NCxPer-yqRtkpV77QVliSglvhpSZ','https://lh3.googleusercontent.com/d/15bdNl0B-eaQBJg8jdLDdM47BWjta1osq','https://lh3.googleusercontent.com/d/1XJMu626m6Rux47yf_tC_SXaIp9u9Gzqv'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:237, nombre:'Arsenal Edición Especial 26/27',                  liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/10MCqcBwuKhBjedDvccFSfdssfBHYWvpJ','https://lh3.googleusercontent.com/d/18t31fMQ0aQVa9ZGm-j-gIMnjG3Du_glr','https://lh3.googleusercontent.com/d/1uemJJ4nzQzChkfZI_FC0XheTK9TcHP8q','https://lh3.googleusercontent.com/d/1ElpBlSEZyvX8TtHAQoqrLubyvDDDlxZ8'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:238, nombre:'Arsenal Edición Especial II 26/27',               liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1mEhhVhf8Rs7vgLr2lvLK5GxaiFk0wSRP','https://lh3.googleusercontent.com/d/1JX2KRgeojusoXIe6ZXLJxq4EnR69qb92','https://lh3.googleusercontent.com/d/1DwI-ww6e3rE2LU7ykXnF3Rq2VU6-sM8N','https://lh3.googleusercontent.com/d/1pkDMg6iOJcsF5xL6czQp701k2Ldo4YQo'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:239, nombre:'Arsenal Equipación Entrenamiento 26/27',          liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1vmLILBIUz8OxCl_0zhSPzTS5wpJIMIVi','https://lh3.googleusercontent.com/d/1s6GvVyLOfePMZsQunfZKkrezrOuzGhwn','https://lh3.googleusercontent.com/d/1s8pXE-9AdUm0oPPXC-o-kNOGlHpOIyyr','https://lh3.googleusercontent.com/d/1GeU6hSYwY1iiqdGY5vXj7BVZBYxw1Hcb'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:240, nombre:'Arsenal Equipación Entrenamiento II 26/27',       liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/19DUENDF8KeiKUhPn44BeTTWc2aQDlvVP','https://lh3.googleusercontent.com/d/11C9_AWtbXK7CP6TAELiDYyzIdq_FTJ-u','https://lh3.googleusercontent.com/d/15wMg03DwCpV0NAJAWKEzUoEHJxaSD348','https://lh3.googleusercontent.com/d/1xFIQ7ohvha4E_pBfn5FTlKckotawuYzo'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:241, nombre:'Manchester United Portero 2ª Equipación 26/27',   liga:'premier',     categoria:['premier'],
      imgs:['https://lh3.googleusercontent.com/d/1NhXY50l2MnBY9uYUERjB2mDpTQ-KBFsC','https://lh3.googleusercontent.com/d/1qxKiVMXDwwe7KieOfYmD6R1vkRNrPpDq','https://lh3.googleusercontent.com/d/16EhasFNXJCMEY-QZhOfd5isVbIPMzhMR','https://lh3.googleusercontent.com/d/16w11l82xDHx1lbydaMEkhnxMQ5VEckwa'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    // ── BUNDESLIGA nuevas 26/27 ──
    { id:242, nombre:'Bayer Leverkusen 2ª Equipación 26/27',            liga:'bundesliga',  categoria:['bundesliga'],
      imgs:['https://lh3.googleusercontent.com/d/1SPte3FYE7ncl3cv37BzYT9pSoV29sZwZ','https://lh3.googleusercontent.com/d/1N6OsjJXEmrwYHbMBjMp32eMP5X1aUy8f','https://lh3.googleusercontent.com/d/1icpwIAQH1WkVvywY-YOF_4Qe0PN8RcBM','https://lh3.googleusercontent.com/d/1LvKCwSbZNlbDg4ADuaRbO79TSPY7TdiC'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:243, nombre:'Bayer Leverkusen 1ª Equipación 26/27',            liga:'bundesliga',  categoria:['bundesliga'],
      imgs:['https://lh3.googleusercontent.com/d/10Y-JSaQg-RIOJQJJIxNlEuee7sxIb5hp','https://lh3.googleusercontent.com/d/1q27XrPxMJZ5dymW9ae9N5B8wXAl4pqgK','https://lh3.googleusercontent.com/d/1yg-isdK0kQ0gz0PdBQtYleeAMCF7bndK','https://lh3.googleusercontent.com/d/1RVXnY2PgjUX4mEDqEPpMy_zUwadipx12'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:244, nombre:'RB Leipzig 1ª Equipación 26/27',                  liga:'bundesliga',  categoria:['bundesliga'],
      imgs:['https://lh3.googleusercontent.com/d/1TcL6vt7SRj9yfZtCh9kZvaAkqHhY2cj8','https://lh3.googleusercontent.com/d/1VKD_t7DacEP-d6lr6rT6aiL2SYjqMnc-','https://lh3.googleusercontent.com/d/1N9P3hLwZ_WTSz1cMvKlL24eVP997LE7t','https://lh3.googleusercontent.com/d/1-vsgOp1dj6QmS7NtH_CGv6rF8DWx4yuk'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:245, nombre:'Bayern München 3ª Equipación 26/27',              liga:'bundesliga',  categoria:['bundesliga'],
      imgs:['https://lh3.googleusercontent.com/d/1MfJQ4LUWyRSE8z0WBewTOawZvo9G1zAz','https://lh3.googleusercontent.com/d/1Ei3oe4nMFl6z303tLlhRvB1-as219Hav','https://lh3.googleusercontent.com/d/1u2ZdJYRXahUeypwn9DbzqkXfcURe-x9Y','https://lh3.googleusercontent.com/d/1MPcV5B-1cfCIxZJ0J7C-1cmwTmUkEdUo'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:246, nombre:'Borussia Dortmund 3ª Equipación 26/27',           liga:'bundesliga',  categoria:['bundesliga'],
      imgs:['https://lh3.googleusercontent.com/d/1bGFoj_aeaHBeWsiIKjTCo3V1d-MA1K5Q','https://lh3.googleusercontent.com/d/1jbO-9DFH6lEUYuttbJawMaYojpbgAuWO','https://lh3.googleusercontent.com/d/1L35e8GZqAEnrl3I3ZJQlOK-jfF3ByV13','https://lh3.googleusercontent.com/d/1fOg7RFv3y0Z3nsz2ptODLZCGVpaLiAyF'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:247, nombre:'Bayern München Equipación Entrenamiento 26/27',   liga:'bundesliga',  categoria:['bundesliga'],
      imgs:['https://lh3.googleusercontent.com/d/1DR7W0bo-VNF6sXWaBFkDWHsPc5iaPAPS','https://lh3.googleusercontent.com/d/1MpNRRZVXghLv_nVfDEmuolNWrMTG20m3','https://lh3.googleusercontent.com/d/1XyRGza1Q7as74Q4u9KzkWoVpYdaBz3I7','https://lh3.googleusercontent.com/d/1LJpwWynVI_5hNAW0u8yb1Z2n-W5vDvAf'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:248, nombre:'Bayern München Equipación Entrenamiento II 26/27',liga:'bundesliga',  categoria:['bundesliga'],
      imgs:['https://lh3.googleusercontent.com/d/1iZUdxcrW2RG_cUTk-5d3PyDzhgVE6y3H','https://lh3.googleusercontent.com/d/1zISc712GCsABYALa-psyHxlGKMBVJZjt','https://lh3.googleusercontent.com/d/1SbvSS3J49RwUj8Pamw0cbnM6MnsWs4bt','https://lh3.googleusercontent.com/d/1CTambcApBdsKr71h72WbnNwGUcZ0aISO'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    // ── LIGUE 1 nuevas 26/27 ──
    { id:249, nombre:'AS Mónaco 2ª Equipación 26/27',                   liga:'ligue1',      categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/1JpFztruuG6eyKfEpkzHGJFkLdcEbDE5f','https://lh3.googleusercontent.com/d/11276RrefeD7A0PERemNL8YFdsPeAfTfc','https://lh3.googleusercontent.com/d/1bFYH5Es051Gw6OsCjKIENHF_RcbDTykb','https://lh3.googleusercontent.com/d/1M4K7uPypyf82TnI9caREBAzM_DErkPnz'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:250, nombre:'Olympique de Marsella 3ª Equipación 26/27',       liga:'ligue1',      categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/1thG9yPlN0IuO6FGHV1oZVeRRsydqjdGk','https://lh3.googleusercontent.com/d/1HzDhCcveeIXew7LuGvTGsBCrsop3CaHp','https://lh3.googleusercontent.com/d/1ybHUISv2RQQNWmeMsXAfMJkiypJWy7F0','https://lh3.googleusercontent.com/d/1arIyucTzRjbzH_OZXdbvwPu-MjnTvpDt'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:251, nombre:'AS Mónaco 3ª Equipación 26/27',                   liga:'ligue1',      categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/1QbmUChuFY2pZ8rQ9zyAPtd2galhu1KMr','https://lh3.googleusercontent.com/d/1DOWshovZlUT9dAg7b9yF3BLetcFZEX7X','https://lh3.googleusercontent.com/d/1hLHtEWExpMr8Kim60d0P5wZnEHnnVSJI','https://lh3.googleusercontent.com/d/19ShFroW39UzeZP3ZRvEdim1V3eQSam8e'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:252, nombre:'Lille 2ª Equipación 26/27',                       liga:'ligue1',      categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/1_khtxF0MEP8mQRE0Inz5_2qxtPCuDiB1','https://lh3.googleusercontent.com/d/1TzObH3Xxb_dN9FWd_5nV_3eRf5N_ACDN','https://lh3.googleusercontent.com/d/19hGRu5ami468xQh4C-jEP8f8HAqM1ifE','https://lh3.googleusercontent.com/d/1D9guDY0WG8ymJrxCIAkl-LvmU_enWKJC'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:253, nombre:'Paris FC 2ª Equipación 26/27',                    liga:'ligue1',      categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/1mlVHQDcRjNLoYmLaeAH8PAvy7GW5R4Wj','https://lh3.googleusercontent.com/d/1RMd103iU5s1bSTRxfJsrA1ByaaKuu3QH','https://lh3.googleusercontent.com/d/1Ms1TZK0h7_ZC3NvRFVDwAfzHTRatnKaJ','https://lh3.googleusercontent.com/d/1caN4prQxGbGNV2vmrnmvhNHWxtZd6LwD'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:254, nombre:'Paris FC 1ª Equipación 26/27',                    liga:'ligue1',      categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/1OWTTwwO4lsO_3rZgbQIFpWJidFCwJbYA','https://lh3.googleusercontent.com/d/1U_8EWT6IgGeSdyxzP5ZbczemNWmaM7YG','https://lh3.googleusercontent.com/d/1EmnbUHLqCT-uJViZLSB-pswNJifQShyQ','https://lh3.googleusercontent.com/d/1xahZyRUmjGdDuKtwFLUFSKuJQig8qYcr'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:255, nombre:'PSG Equipación Entrenamiento 26/27',              liga:'ligue1',      categoria:['ligue1'],
      imgs:['https://lh3.googleusercontent.com/d/13QrlxtdZe3rGyVeCurIR4G2icxezt8eJ','https://lh3.googleusercontent.com/d/16sPiG0Ldz89I4AbRZjgkvWPloQt6MFJv','https://lh3.googleusercontent.com/d/12otqJAmcOXfR5aJjFxh5jOe7i19g1ts1','https://lh3.googleusercontent.com/d/1JJyIE8vegQtvOmrHyBD7OwegySNuYV3z'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    // ── SERIE A nuevas 26/27 ──
    { id:256, nombre:'Juventus 3ª Equipación 26/27',                    liga:'seriea',      categoria:['seriea'],
      imgs:['https://lh3.googleusercontent.com/d/1MacpPS4r--sjT9XOd-wi34wmNVvPIzkQ','https://lh3.googleusercontent.com/d/1bIQrUxnEzwIM3tCI1_EK0Adrqw3cYT2v','https://lh3.googleusercontent.com/d/1gm-wceYdrbHn4VeqEuBDUrykn6HvY8oX','https://lh3.googleusercontent.com/d/1dxT9dFZ0p2kx5RovWRep1ExZRc8SWzpH'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:257, nombre:'Napoli 3ª Equipación 26/27',                      liga:'seriea',      categoria:['seriea'],
      imgs:['https://lh3.googleusercontent.com/d/1kb-matSHtO2ObTJPoj_jtM0Oy6916qbo','https://lh3.googleusercontent.com/d/1gNJ2dR3MRJdAgsir6OLtxNeGZVhaexPe','https://lh3.googleusercontent.com/d/1uZEGZA0kCRwUfs007PRMuX-m4syFo-jd','https://lh3.googleusercontent.com/d/14RCag053_ik2uLm4mu0Sjfx7qJSV5BIJ'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:258, nombre:'Inter de Milán 2ª Equipación 26/27',              liga:'seriea',      categoria:['seriea'],
      imgs:['https://lh3.googleusercontent.com/d/1XDdh3SWjXsQbbdPSD9edxrKIlDyy5Irc','https://lh3.googleusercontent.com/d/1nqgbNMMiDmJsZAV8DyHwEUAOc0SxFNZu','https://lh3.googleusercontent.com/d/1jnIjt5ZgTPRB3KzL5Eag5h4EoXBfRJ_5','https://lh3.googleusercontent.com/d/1dpMDdX7AX3ANf9YwY20F5JyD-TqLABDn'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:259, nombre:'AS Roma 2ª Equipación 26/27',                     liga:'seriea',      categoria:['seriea'],
      imgs:['https://lh3.googleusercontent.com/d/1_mQ8uleJ1nrdUcfxHS0FDaHTVrX5B7PG','https://lh3.googleusercontent.com/d/1zxY9CPnxvUAnb9hiAlxus3WxMw0WvM_1','https://lh3.googleusercontent.com/d/1N-wmGNsrn6TZ815dt5RcdLCfvjJ4abQ6','https://lh3.googleusercontent.com/d/1zebcQseqQxmuuA8jfuLt4nFpRYNJXaBX'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:260, nombre:'Juventus Equipación Entrenamiento 26/27',         liga:'seriea',      categoria:['seriea'],
      imgs:['https://lh3.googleusercontent.com/d/1a6z5ZaD-6chUQUGoj8ZEKS2Z-vzoEMgk','https://lh3.googleusercontent.com/d/1G09_O0O_yaKBBi4ElIzgMmA5Ma2nXZ9u','https://lh3.googleusercontent.com/d/1g9avSEVLzv0Z43elOAh2Kv9ZixTbeym7'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:261, nombre:'Juventus Equipación Entrenamiento II 26/27',      liga:'seriea',      categoria:['seriea'],
      imgs:['https://lh3.googleusercontent.com/d/1SeTLlyjCFqqvezlTlAvuQ35vw_Zh20yd','https://lh3.googleusercontent.com/d/1nZsTkb1SOkrkHUA3KaKIkxA9ZMmyiAnD','https://lh3.googleusercontent.com/d/1FOmHMIl8ast0qtBU9zUfUox0xSZOcPKQ'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:262, nombre:'Juventus Equipación Entrenamiento III 26/27',     liga:'seriea',      categoria:['seriea'],
      imgs:['https://lh3.googleusercontent.com/d/1ermg9Vv-o0gp_0vdA8xUswBoR1WJlbLN','https://lh3.googleusercontent.com/d/1mtsMXwaLtT8iv0rV3lXrav_jKQqNiilQ','https://lh3.googleusercontent.com/d/1sXaYRAQt9BCHxcL9dDMoWyBwU3FTEG5j','https://lh3.googleusercontent.com/d/1PenDV8njn411nU7LOG3FQPylPL_9eVje'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    // ── OTRAS LIGAS nuevas 26/27 ──
    { id:263, nombre:'Inter de Miami 1ª Equipación 26/27',             liga:'otros',       categoria:['otros'],
      imgs:['https://lh3.googleusercontent.com/d/10Yxk2GC6cpZz45KKyhwlVzS6dsxUyX4z','https://lh3.googleusercontent.com/d/1sc9uXPFQ6wNnEury9UadudoncULh56cQ','https://lh3.googleusercontent.com/d/15pWEk57ScKkd_rii8vC3gQf4m-fzBFsr','https://lh3.googleusercontent.com/d/1qdeUAt0a5upI_zLgXzSaIbiAldlgdZLg'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:264, nombre:'Sporting de Lisboa 1ª Equipación 26/27',         liga:'primeiraliga',categoria:['primeiraliga'],
      imgs:['https://lh3.googleusercontent.com/d/1K0EJA1TW2kXu3xKjFotvIDz1A1CRqm4T','https://lh3.googleusercontent.com/d/1DLCwvsz4mpFahNMo5NFkdngvgyYByE9q','https://lh3.googleusercontent.com/d/1Rao8m4Ylc0aKpscBMeLHRCYd3i9wqWRS','https://lh3.googleusercontent.com/d/1xx5mHwReHDxyKROXgnwCGAoHAouX6Vdo'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:265, nombre:'Sporting de Lisboa 2ª Equipación 26/27',         liga:'primeiraliga',categoria:['primeiraliga'],
      imgs:['https://lh3.googleusercontent.com/d/1U7H1UnkPn4fWLidFhiGEmtZOMeWQOW3A','https://lh3.googleusercontent.com/d/1pKn67XcWP15qys0PuyT_Zwy3Ff9BipKk','https://lh3.googleusercontent.com/d/1sYkN2uH0Mu2bb1n9D2wRgTq2KYKTsgJw','https://lh3.googleusercontent.com/d/1K62jX8_MTEY0kUEOiS0jzUju8RFzW2tX'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:266, nombre:'Galatasaray 1ª Equipación 26/27',                liga:'superlig',    categoria:['superlig'],
      imgs:['https://lh3.googleusercontent.com/d/1JQzgk-Xq42i01crE8wsJ2iuMtp3JPCOE','https://lh3.googleusercontent.com/d/1zGZVvh3WF_OI2kB8MZ3XHkHua5LhDp3b','https://lh3.googleusercontent.com/d/1jJ1bUNlGWkKjsWosw54EtQ6LHFZTkYjU','https://lh3.googleusercontent.com/d/1bpnMBZMK1IxibSAhuOLSs27fQAj7nHz1'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:267, nombre:'Galatasaray 3ª Equipación 26/27',                liga:'superlig',    categoria:['superlig'],
      imgs:['https://lh3.googleusercontent.com/d/1etweVyJyC25mpeARFoTB6pzChijYdZa-','https://lh3.googleusercontent.com/d/1LKbvpXZag0yoTKGjQosm2ntEejwDPzIh','https://lh3.googleusercontent.com/d/1mjGT-4KKJmfCU-p2itfz9rVs3qrCCbuQ','https://lh3.googleusercontent.com/d/1YVYJY-jJSrgTno4DQjEoXjoiUHn2fHRI'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:268, nombre:'Ajax 2ª Equipación 26/27',                       liga:'eredivisie',  categoria:['eredivisie'],
      imgs:['https://lh3.googleusercontent.com/d/1V6n-OWNXcnx4EKEKMUUP22Y3mg4W4iII','https://lh3.googleusercontent.com/d/1ASGKZ2GIjxpo-IzDUkkXkmDunNVQ46vO','https://lh3.googleusercontent.com/d/1cHdus192LtXHLTEv8Bhe03cBo0UvcKg-','https://lh3.googleusercontent.com/d/1ziExdkPO3hul-ZK09t5SAz7IR1Vesaaq'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:269, nombre:'Celtic FC 2ª Equipación 26/27',                  liga:'otros',       categoria:['otros'],
      imgs:['https://lh3.googleusercontent.com/d/19KH6iapQDpNeNONFLggIsgoyS45IzAt-','https://lh3.googleusercontent.com/d/1X7QskGO2Y5UzymAvxfD6q3XEYiUKIJ3K','https://lh3.googleusercontent.com/d/1x7z1NNkhzghhK7rzXpiuXzuYOy_qiHtT','https://lh3.googleusercontent.com/d/1u6Y3VrhlpVIB7YmQoYyb8ZNv8Ootdt5X'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:270, nombre:'Rayados de Monterrey 2ª Equipación 26/27',       liga:'otros',       categoria:['otros'],
      imgs:['https://lh3.googleusercontent.com/d/129slrVksd2ynCnBXVZKStbaeWGtftu7J','https://lh3.googleusercontent.com/d/1H0JCGo8HHis8QpP9rEcYTSgmZ9qC_iAi','https://lh3.googleusercontent.com/d/1wuWCE_UTnXDQRgwhCQKLPHXCjHP0GSI1','https://lh3.googleusercontent.com/d/1KNtjir247TpRfi7CYGq09mPjbdIXPD2t'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:271, nombre:'Al-Ahli 1ª Equipación 26/27',                    liga:'saudi',       categoria:['saudi'],
      imgs:['https://lh3.googleusercontent.com/d/11i5EbQBnQTOqBAlBp-HnzKA_NaXkGQOm','https://lh3.googleusercontent.com/d/1gRw_966iNLUIDAeFMxPpTGyG7ymaGVW6','https://lh3.googleusercontent.com/d/1MA5-8jqTCmisWbsGmiKvRtz1GLwZhFdn','https://lh3.googleusercontent.com/d/1BD2K0VMDwkSE8lFmpo08JDwmysweZODz'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:272, nombre:'Al-Ahli 2ª Equipación 26/27',                    liga:'saudi',       categoria:['saudi'],
      imgs:['https://lh3.googleusercontent.com/d/1gXnEXPbj9QK7DjLloNN9kpUNPCpA4oi3','https://lh3.googleusercontent.com/d/1oVmKgXd9PUv9etNPfMHZRK7smRyFP_ys','https://lh3.googleusercontent.com/d/1bKQbz3UXeWAgHrr0fbkFIUu7uqfIXOYk','https://lh3.googleusercontent.com/d/16vq1j6m4W_ixCPvTMUd_Re0aDrZyMUNn'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:273, nombre:'Club América Edición Especial 26/27',            liga:'otros',       categoria:['otros'],
      imgs:['https://lh3.googleusercontent.com/d/1mr6VNRrWx_h7RfGzPNFok8RzmKX7nwVc','https://lh3.googleusercontent.com/d/1ENMFm4vjtqVdc1IsrZaFy-HR9EcvNoxT','https://lh3.googleusercontent.com/d/1aI2bVFsPO4RReIOTzMuSn0w1HIS3UVBa','https://lh3.googleusercontent.com/d/11VjDmKdkNDg2ykww8Ngc-583pa6ASrhQ'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    { id:274, nombre:'Al Hilal 3ª Equipación 26/27',                   liga:'saudi',       categoria:['saudi'],
      imgs:['https://lh3.googleusercontent.com/d/1K6EKIKI3BSN5omGTcLgjU6A2QaTPrnNC','https://lh3.googleusercontent.com/d/1CxU9M5ZW6_E7eX6kRgRkwubV5RZPF6Zh','https://lh3.googleusercontent.com/d/1bnDtZQvnZq8ZRmyLz6kh7ExHSnV1uiAI','https://lh3.googleusercontent.com/d/1KwDB9MMQpSOZQIEPQ5Rd0RjUZwZwY4kE'],
      tipo:'regular', badge:'nuevo', badgeTexto:'Nuevo' },
    // ════════════════════════════════════════════════════════
    // ── RETRO ──
    // ════════════════════════════════════════════════════════
    { id:101, nombre:'Real Madrid 02/03 Primera Equipación',                 liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'E7ed/e6908738.jpeg',CDN+'mRlG/5e902d8c.jpeg',CDN+'6QdU/d11afc34.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro', orden:6 },
    { id:102, nombre:'Rayo Vallecano 01/02 Primera Equipación',              liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'INlT/12d6c9df.jpeg',CDN+'OeO3/a6ac1585.jpeg',CDN+'x9Jh/e759c66d.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:103, nombre:'PSV 94/95 Primera Equipación',                         liga:'retro', categoria:['retro','eredivisie'],  imgs:[CDN+'d0gq/c3f28f21.jpeg',CDN+'vPYo/7064644a.jpeg',CDN+'1LgE/d806082d.jpeg',CDN+'ixXb/3efad366.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:104, nombre:'Portugal 2004 Segunda Equipación',                     liga:'retro', categoria:['retro','selecciones'], imgs:[CDN+'zDmj/f480da02.jpg',CDN+'2TGy/11c494ce.jpg',CDN+'v6ie/5b35f4e9.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:105, nombre:'Países Bajos 2014 Primera Equipación',                 liga:'retro', categoria:['retro','selecciones'], imgs:[CDN+'fZ0Q/c7c3d5a9.jpg',CDN+'lzoi/e566b1d2.jpg',CDN+'zNQR/228de161.jpg',CDN+'wlk0/4260402b.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:106, nombre:'Oviedo 96/97 Primera Equipación',                      liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'pMZr/929a4043.jpg',CDN+'M4iN/6fa1e455.jpg',CDN+'NUPr/7e064f63.jpg',CDN+'lPvw/748ceeef.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:107, nombre:'Osasuna 95/97 Primera Equipación',                     liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'RSD5/8f105dc6.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:108, nombre:'AC Milan 125 Aniversario Primera Equipación',          liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'uUAj/d7992dbc.jpeg',CDN+'EhOZ/de8e7de0.jpeg',CDN+'5uAd/d384a287.jpeg',CDN+'QfgB/f5ccb3d5.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:109, nombre:'Inter Milan 94/95 Segunda Equipación',                 liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'moxp/7dc0a7ec.jpeg',CDN+'wgAI/caf126b5.jpeg',CDN+'XwNX/52494ebd.jpeg',CDN+'Iwdw/a7eb7cd8.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:110, nombre:'AC Milan 99/00 Segunda Equipación',                    liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'AzXq/13c63def.jpeg',CDN+'RoEQ/b57745ff.jpeg',CDN+'5Xcx/80d2cd69.jpeg',CDN+'8fjY/47c35204.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:111, nombre:'Manchester United 98/99 Tercera Equipación',           liga:'retro', categoria:['retro','premier'],     imgs:[CDN+'YK7r/95d82686.jpeg',CDN+'nbM3/91f15671.jpeg',CDN+'XWd5/2f535c8d.jpeg',CDN+'tiNw/d824c8ab.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:112, nombre:'Manchester United 03/05 Segunda Equipación',           liga:'retro', categoria:['retro','premier'],     imgs:[CDN+'lD4E/854792b4.jpeg',CDN+'Q04n/10522cf1.jpeg',CDN+'Auj2/e2de9492.jpeg',CDN+'hjcE/f6297c5f.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:113, nombre:'Manchester United 04/05 Segunda Equipación',           liga:'retro', categoria:['retro','premier'],     imgs:[CDN+'lD4E/854792b4.jpeg',CDN+'Q04n/10522cf1.jpeg',CDN+'Auj2/e2de9492.jpeg',CDN+'hjcE/f6297c5f.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:114, nombre:'Manchester City 12/13 Segunda Equipación',             liga:'retro', categoria:['retro','premier'],     imgs:[CDN+'YyaC/8168cf26.jpeg',CDN+'Zxhb/3fb8968d.jpeg',CDN+'qQqt/0cdd579a.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:115, nombre:'Málaga 05/06 Primera Equipación',                      liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'zMpL/2373aee3.jpeg',CDN+'rGoe/645af5eb.jpeg',CDN+'QcZ0/dd7d1e7f.jpeg',CDN+'frhj/e65fc413.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:116, nombre:'Málaga CF 10/11 Primera Equipación',                   liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'muGE/ce3b2773.jpeg',CDN+'3Ob4/7ccd83e1.jpeg',CDN+'ZAQJ/88e43abc.jpeg',CDN+'Y8VA/127fafd9.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:117, nombre:'Lyon 10/11 Primera Equipación',                        liga:'retro', categoria:['retro','ligue1'],   imgs:[CDN+'TxgE/d8ea4c23.jpeg',CDN+'zyPa/db1eda42.jpeg',CDN+'Vdpg/d0c04530.jpeg',CDN+'x2k7/1e338e91.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:118, nombre:'Inter de Milán 95/96 Primera Equipación',              liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'xn6l/82109876.jpeg',CDN+'gCbE/9f349868.jpeg',CDN+'glFd/3953b8b7.jpeg',CDN+'W8Kf/5b90df7c.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:119, nombre:'Inter de Milán 02/03 Primera Equipación',              liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'AYKh/4aabd8c5.jpeg',CDN+'Q5Ra/509d8096.jpeg',CDN+'zlnU/59de4b7c.jpeg',CDN+'miBJ/c3222459.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:120, nombre:'Inter de Milán 97/98 Primera Equipación',              liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'bBbE/5ddcb9aa.jpeg',CDN+'QL5I/c8c50e79.jpeg',CDN+'JpVv/8d42aad5.jpeg',CDN+'vzX6/da9e67b0.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:121, nombre:'Granada CF 98/99 Primera Equipación',                  liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'ZgTx/be45bbcc.jpeg',CDN+'XRiX/14e73bdb.jpeg',CDN+'T7cM/25b9630c.jpeg',CDN+'OlgZ/32be9ef9.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:122, nombre:'Getafe CF 97/98 Primera Equipación',                   liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'LXSx/b70be590.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:123, nombre:'Fiorentina 95/96 Tercera Equipación',                  liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'u89H/6f828320.jpg',CDN+'BLm7/af73c064.jpg',CDN+'dmcB/593f3e76.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:124, nombre:'Fiorentina 02/03 Primera Equipación',                  liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'g4GO/c6f34e51.jpeg',CDN+'Bw3M/5082bfca.jpeg',CDN+'Tdyh/710c90ae.jpeg',CDN+'zp5t/4fe7c2b1.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:125, nombre:'FC Barcelona 98/99 Tercera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'lduZ/27064009.jpeg',CDN+'FwYa/c3bd97f9.jpeg',CDN+'jo0a/92140080.jpeg',CDN+'IDdU/c3c3e8c9_1.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:126, nombre:'FC Barcelona 13/14 Tercera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'g3MQ/35dde3b5.jpg',CDN+'E0XA/1bea333f.jpg',CDN+'Eirn/9573a345.jpg',CDN+'2rML/a5b5b538.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:127, nombre:'FC Barcelona 82/84 Segunda Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'vjXE/ca40be39.jpeg',CDN+'pQR7/aa6010af.jpeg',CDN+'t0V5/440c5184.jpeg',CDN+'jCRn/7efa9ffc.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:128, nombre:'FC Barcelona 07/08 Segunda Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'FdnW/3a5bcd9e.jpg',CDN+'4QJo/3985e9d0.jpg',CDN+'H4H7/77537b74.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:129, nombre:'FC Barcelona 03/04 Segunda Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'Vkao/433125f6.jpeg',CDN+'choP/cd5475d5.jpeg',CDN+'7Q3R/ec7e5327.jpeg',CDN+'liWo/4df9226a.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:130, nombre:'FC Barcelona 96/97 Primera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'LZJn/c69b9942.jpeg',CDN+'pLvt/707e5872.jpeg',CDN+'pNYQ/2c362639.jpeg',CDN+'Yj0l/51decf61.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:131, nombre:'FC Barcelona 91/92 Primera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'5USs/32543de8.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:132, nombre:'FC Barcelona 09/10 Primera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'aEeS/bee40eb8.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:133, nombre:'FC Barcelona 08/09 Final Champions',                   liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'wiq9/c82ba79b.jpeg',CDN+'iCt6/b3eccafc.jpeg',CDN+'WRQB/678cba2b.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:134, nombre:'FC Barcelona 05/06 Primera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'i0i2/89cfacfc.jpeg',CDN+'fqFb/f493627d.jpeg',CDN+'yxoV/583cc8c7.jpeg',CDN+'rT82/177cf4d5.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:135, nombre:'España 2000 Segunda Equipación',                       liga:'retro', categoria:['retro','selecciones'], imgs:[CDN+'ixyt/55cef3e5.jpeg',CDN+'0xBC/9d7de6a2.jpeg',CDN+'xWvo/51e2f324.jpeg',CDN+'NtU3/2da31b85.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:136, nombre:'España 2000 Primera Equipación',                       liga:'retro', categoria:['retro','selecciones'], imgs:[CDN+'Mnyq/fc90a84d.jpeg',CDN+'J3C3/479ed808.jpeg',CDN+'Lptd/085a1214.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:137, nombre:'Deportivo De La Coruña 99/00 Segunda Equipación',      liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'gsBT/b7945518.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:138, nombre:'Deportivo De La Coruña 97/98 Primera Equipación',      liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'RZq6/3504270a.jpeg',CDN+'E9Zh/485b2c11.jpeg',CDN+'oZti/5334dabe.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:139, nombre:'Celta de Vigo 99/00 Primera Equipación',               liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'Vr1T/f33f3d64.jpeg',CDN+'rEqc/d68532f5.jpeg',CDN+'8i9K/285e548a.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:140, nombre:'Celta de Vigo 83/84 Primera Equipación',               liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'2Exy/8ab6cc4f.jpeg',CDN+'t1lg/e769571b.jpeg',CDN+'CQBA/3d22c924.jpeg',CDN+'Dmfx/12de8fd1.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:141, nombre:'Cádiz CF 89/90 Primera Equipación',                    liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'Gp72/969ed866.jpg',CDN+'iWau/85ce6d3c.jpg',CDN+'nKB0/97a96da0.jpg',CDN+'2iF4/a7423cff.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:142, nombre:'Brasil 2004 Primera Equipación',                       liga:'retro', categoria:['retro','selecciones'], imgs:[CDN+'mh28/ba8c8c85.jpg',CDN+'Wb2W/1bd1841c.jpg',CDN+'uMUH/a0eb6d7c.jpg',CDN+'deKq/6b4be19c.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:143, nombre:'Boca Juniors 93/94 Primera Equipación',                liga:'retro', categoria:['retro'],               imgs:[CDN+'swUg/2ee7a44c.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:144, nombre:'Betis 88/89 Primera Equipación',                       liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'dHK6/2eb2049e.jpeg',CDN+'f3Vj/ac08bcbd.jpeg',CDN+'7Avg/870a6d8c.jpeg',CDN+'ydZb/6b5e4e1d.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:145, nombre:'Betis 95/96 Primera Equipación',                       liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'QtVq/63d40db9.jpeg',CDN+'PcZ9/b4ac992f.jpeg',CDN+'1JMk/c0b85352.jpeg',CDN+'TLnt/b0cea0a9.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:146, nombre:'Real Betis 97/99 Segunda Equipación',                  liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'JNEI/57bd3d37.jpeg',CDN+'cLf8/53a87ff5.jpeg',CDN+'mMhM/c80ac0be.jpeg',CDN+'11CM/ef4bbc65.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:147, nombre:'Benfica 14/15 Primera Equipación',                    liga:'retro', categoria:['retro','primeiraliga'], imgs:[CDN+'HELW/dd90e61b.jpg',CDN+'2G0k/b49ee3af.jpg',CDN+'OLtg/389c65a7.jpg',CDN+'kMeR/27f2f198.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:148, nombre:'Bayern München 07/08 Primera Equipación',              liga:'retro', categoria:['retro','bundesliga'],   imgs:[CDN+'Lq4M/56aafb38.jpeg',CDN+'Gb5X/ed156d6e.jpeg',CDN+'Go73/74a7b016.jpeg',CDN+'ZDJX/62ff82c4.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:149, nombre:'Bayern München 05/06 Primera Equipación',              liga:'retro', categoria:['retro','bundesliga'],   imgs:[CDN+'jFjK/ca8b54af.jpg',CDN+'oXOq/337f0f60.jpg',CDN+'fVGi/f38abc2e.jpg',CDN+'6KWe/a04a3fc0.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:150, nombre:'Bayern München 01/02 Primera Equipación',              liga:'retro', categoria:['retro','bundesliga'],   imgs:[CDN+'uErZ/7d17c3e9.jpg',CDN+'dDcH/4781b322.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:151, nombre:'Bayern München 00/01 Primera Equipación',              liga:'retro', categoria:['retro','bundesliga'],   imgs:[CDN+'Mgkn/25742108.jpeg',CDN+'E5dq/f23340ad.jpeg',CDN+'f7AI/cf0e4259.jpeg',CDN+'1IcC/c4f531b7.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:152, nombre:'Bayer Leverkusen 01/02 Primera Equipación',            liga:'retro', categoria:['retro','bundesliga'],   imgs:[CDN+'WoV8/029dc4cd.jpeg',CDN+'twVN/e5a590b5.jpeg',CDN+'GdBn/06e96752.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:153, nombre:'Bayer Leverkusen 97/98 Primera Equipación',            liga:'retro', categoria:['retro','bundesliga'], imgs:[CDN+'SpwW/b79e0d6d.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:154, nombre:'Atlético de Madrid 96/97 Segunda Equipación',          liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'cFRD/3b972921.jpg',CDN+'7lvl/4c243795.jpg',CDN+'KkQG/519e0e44.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:155, nombre:'Atlético de Madrid 99/00 Primera Equipación',          liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'M8lq/84406d33.jpeg',CDN+'aLzK/27a65021.jpeg',CDN+'yCGK/04fbf03e.jpeg',CDN+'eM9l/9f4cf38e.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:156, nombre:'Atlético de Madrid 98/99 Primera Equipación',          liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'dnWz/b002f81f.jpeg',CDN+'rU6d/f9e9629c.jpeg',CDN+'8WWz/b21b8c93.jpeg',CDN+'5JTR/36afdd13.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:157, nombre:'Atlético de Madrid 12/13 Primera Equipación',          liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'x6HE/4c07a71f.jpg',CDN+'fY0f/63aaf819.jpg',CDN+'uPv6/8070e7a5.jpg',CDN+'BRy7/624d6fc0.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:158, nombre:'Atlético de Madrid 04/05 Primera Equipación M/L',      liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'ADyT/8d8268ab.jpg',CDN+'71pt/d35dd711.jpg',CDN+'NOYW/50e5f21a.jpg',CDN+'BhXk/379b5725.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:159, nombre:'Athletic Club Bilbao Edición Centenario',              liga:'retro', categoria:['retro','laliga'],      imgs:[CDN+'uCvd/528c19b8.jpeg',CDN+'X2tJ/097760d1.jpeg',CDN+'JpLo/61ea2ca9.jpeg',CDN+'WEfm/292218ed.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:160, nombre:'AS Roma 92/94 Tercera Equipación',                     liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'3eck/ed7768b3.jpeg',CDN+'N6mJ/74158581.jpeg',CDN+'nRyb/2921470b.jpeg',CDN+'NKyh/5bfadf32.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:161, nombre:'AS Roma 91/92 Tercera Equipación',                     liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'JSzw/d70b2863.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:162, nombre:'AS Roma 92/94 Segunda Equipación',                     liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'gt8e/673fd756.jpeg',CDN+'bejx/5434ad39.jpeg',CDN+'nzn2/92b186af.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:163, nombre:'AS Roma 99/00 Primera Equipación',                     liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'8X76/39fe33c8.jpeg',CDN+'6qm3/81ff15c6.jpeg',CDN+'WiMP/63b66cc9.jpeg',CDN+'AM5Z/b1d37df2.jpeg',CDN+'uf4T/0d8d432b.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:164, nombre:'Arsenal 94/95 Segunda Equipación',                     liga:'retro', categoria:['retro','premier'],     imgs:[CDN+'lJIF/f11b13b5.jpg',CDN+'otm8/884476ec.jpg',CDN+'2xrJ/3913b0ae.jpg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:165, nombre:'Arsenal 93/94 Segunda Equipación',                     liga:'retro', categoria:['retro','premier'],     imgs:[CDN+'gBf9/3b132605.jpeg',CDN+'bfz7/17c72fb1.jpeg',CDN+'rBDn/e9b753f7.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:166, nombre:'Arsenal 02/04 Primera Equipación M/L',                 liga:'retro', categoria:['retro','premier'],     imgs:[CDN+'P9dr/0502cd5e.jpeg',CDN+'XbXy/9e9783cf.jpeg',CDN+'IqUD/cde261d1.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:167, nombre:'Alemania 1986 Primera Equipación',                     liga:'retro', categoria:['retro','selecciones'], imgs:[CDN+'Iz59/a103996b.jpeg',CDN+'hIO8/ab211cc5.jpeg',CDN+'nNMz/962ac2e8.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:168, nombre:'Alemania 02/03 Primera Equipación',                    liga:'retro', categoria:['retro','selecciones'], imgs:[CDN+'kxC4/7ca869d1.jpeg',CDN+'PKua/81a7a8b2.jpeg',CDN+'Bpt1/c26afb6e.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:169, nombre:'AC Milan 03/04 Primera Equipación',                    liga:'retro', categoria:['retro','seriea'],   imgs:[CDN+'Qqik/ac_milan_1a_03_04.jpg',CDN+'yt3E/7f39ef3b.jpeg',CDN+'1IMg/43b63df0.jpeg',CDN+'ub53/ae71a7d1.jpeg'],  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
  ];