const fs = require('fs');
const imgs = JSON.parse(fs.readFileSync('C:/Users/tonim/KitZone/imgs_mapping.json', 'utf8'));

function makeImgs(id) {
  const arr = imgs[String(id)];
  if (!arr || arr.length === 0) return "[]";
  return "[" + arr.map(p => "CDN+'" + p + "'").join(',') + "]";
}

const CAMISETAS_JS = `  const CAMISETAS = [
    // ── TEMPORADA 25/26 · LA LIGA ──
    { id:1,  nombre:'FC Barcelona Edición Especial 25/26',           liga:'laliga',      categoria:['laliga','champions'], imgs:${makeImgs(1)},  tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:2,  nombre:'FC Barcelona Edición Especial 25/26 (II)',      liga:'laliga',      categoria:['laliga','champions'], imgs:${makeImgs(2)},  tipo:'regular', badge:null },
    { id:3,  nombre:'FC Barcelona Edición Especial 25/26 (III)',     liga:'laliga',      categoria:['laliga','champions'], imgs:${makeImgs(3)},  tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · PREMIER LEAGUE ──
    { id:4,  nombre:'Arsenal Primera Equipación 25/26',              liga:'premier',     categoria:['premier','champions'],imgs:${makeImgs(4)},  tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:5,  nombre:'Arsenal Edición Especial 25/26',                liga:'premier',     categoria:['premier','champions'],imgs:${makeImgs(5)},  tipo:'regular', badge:null },
    { id:6,  nombre:'Arsenal Edición Especial 25/26 (II)',           liga:'premier',     categoria:['premier','champions'],imgs:${makeImgs(6)},  tipo:'regular', badge:null },
    { id:7,  nombre:'Arsenal Edición Especial 25/26 (III)',          liga:'premier',     categoria:['premier','champions'],imgs:${makeImgs(7)},  tipo:'regular', badge:null },
    { id:8,  nombre:'Liverpool Tercera Equipación 25/26',            liga:'premier',     categoria:['premier','champions'],imgs:${makeImgs(8)},  tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:9,  nombre:'Chelsea Tercera Equipación 25/26',              liga:'premier',     categoria:['premier','champions'],imgs:${makeImgs(9)},  tipo:'regular', badge:null },
    { id:10, nombre:'Everton Tercera Equipación 25/26',              liga:'premier',     categoria:['premier'],            imgs:${makeImgs(10)}, tipo:'regular', badge:null },
    { id:11, nombre:'Fulham Primera Equipación 25/26',               liga:'premier',     categoria:['premier'],            imgs:${makeImgs(11)}, tipo:'regular', badge:null },
    { id:12, nombre:'Fulham Segunda Equipación 25/26',               liga:'premier',     categoria:['premier'],            imgs:${makeImgs(12)}, tipo:'regular', badge:null },
    { id:13, nombre:'Fulham Tercera Equipación 25/26',               liga:'premier',     categoria:['premier'],            imgs:${makeImgs(13)}, tipo:'regular', badge:null },
    { id:14, nombre:'Crystal Palace Segunda Equipación 25/26',       liga:'premier',     categoria:['premier'],            imgs:${makeImgs(14)}, tipo:'regular', badge:null },
    { id:15, nombre:'Crystal Palace Tercera Equipación 25/26',       liga:'premier',     categoria:['premier'],            imgs:${makeImgs(15)}, tipo:'regular', badge:null },
    { id:16, nombre:'West Ham United Segunda Equipación 25/26',      liga:'premier',     categoria:['premier'],            imgs:${makeImgs(16)}, tipo:'regular', badge:null },
    { id:17, nombre:'Wolverhampton Primera Equipación 25/26',        liga:'premier',     categoria:['premier'],            imgs:${makeImgs(17)}, tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · CHAMPIONS ──
    { id:18, nombre:'Bayern München Segunda Equipación 25/26',       liga:'champions',   categoria:['champions'],          imgs:${makeImgs(18)}, tipo:'regular', badge:null },
    { id:19, nombre:'Bayern München Edición Especial 25/26',         liga:'champions',   categoria:['champions'],          imgs:${makeImgs(19)}, tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:20, nombre:'Inter de Milán Segunda Equipación 25/26',       liga:'champions',   categoria:['champions'],          imgs:${makeImgs(20)}, tipo:'regular', badge:null },
    { id:21, nombre:'Inter de Milán Tercera Equipación 25/26',       liga:'champions',   categoria:['champions'],          imgs:${makeImgs(21)}, tipo:'regular', badge:null },
    { id:22, nombre:'PSG Edición Especial 25/26',                    liga:'champions',   categoria:['champions'],          imgs:${makeImgs(22)}, tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:23, nombre:'Ajax Edición Especial 25/26',                   liga:'champions',   categoria:['champions'],          imgs:${makeImgs(23)}, tipo:'regular', badge:null },
    { id:24, nombre:'Ajax Edición Especial 25/26 (II)',              liga:'champions',   categoria:['champions'],          imgs:${makeImgs(24)}, tipo:'regular', badge:null },
    { id:25, nombre:'Ajax Edición Especial 25/26 (III)',             liga:'champions',   categoria:['champions'],          imgs:${makeImgs(25)}, tipo:'regular', badge:null },
    { id:26, nombre:'Ajax Segunda Equipación 25/26',                 liga:'champions',   categoria:['champions'],          imgs:${makeImgs(26)}, tipo:'regular', badge:null },
    { id:27, nombre:'AS Roma Segunda Equipación 25/26',              liga:'champions',   categoria:['champions'],          imgs:${makeImgs(27)}, tipo:'regular', badge:null },
    { id:28, nombre:'Bayer Leverkusen Segunda Equipación 25/26',     liga:'champions',   categoria:['champions'],          imgs:${makeImgs(28)}, tipo:'regular', badge:null },
    { id:29, nombre:'Galatasaray Primera Equipación 25/26',          liga:'champions',   categoria:['champions'],          imgs:${makeImgs(29)}, tipo:'regular', badge:null },
    { id:30, nombre:'Galatasaray Segunda Equipación 25/26',          liga:'champions',   categoria:['champions'],          imgs:${makeImgs(30)}, tipo:'regular', badge:null },
    { id:31, nombre:'Napoli Tercera Equipación 25/26',               liga:'champions',   categoria:['champions'],          imgs:${makeImgs(31)}, tipo:'regular', badge:null },
    { id:32, nombre:'Lille Primera Equipación 25/26',                liga:'champions',   categoria:['champions'],          imgs:${makeImgs(32)}, tipo:'regular', badge:null },
    { id:33, nombre:'Lille Segunda Equipación 25/26',                liga:'champions',   categoria:['champions'],          imgs:${makeImgs(33)}, tipo:'regular', badge:null },
    { id:34, nombre:'Monaco Tercera Equipación 25/26',               liga:'champions',   categoria:['champions'],          imgs:${makeImgs(34)}, tipo:'regular', badge:null },
    { id:35, nombre:'Marsella Tercera Equipación 25/26',             liga:'champions',   categoria:['champions'],          imgs:${makeImgs(35)}, tipo:'regular', badge:null },
    { id:36, nombre:'Sporting de Portugal Tercera Equipación 25/26', liga:'champions',   categoria:['champions'],          imgs:${makeImgs(36)}, tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · SELECCIONES ──
    { id:37, nombre:'Italia Primera Equipación Mundial 2026',        liga:'selecciones', categoria:['selecciones'],        imgs:${makeImgs(37)}, tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:38, nombre:'Colombia Primera Equipación Mundial 2026',      liga:'selecciones', categoria:['selecciones'],        imgs:${makeImgs(38)}, tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:39, nombre:'México Primera Equipación Mundial 2026',        liga:'selecciones', categoria:['selecciones'],        imgs:${makeImgs(39)}, tipo:'regular', badge:'nuevo',  badgeTexto:'Nuevo' },
    { id:40, nombre:'Marruecos Primera Equipación 2025',             liga:'selecciones', categoria:['selecciones'],        imgs:${makeImgs(40)}, tipo:'regular', badge:null },
    { id:41, nombre:'Marruecos Segunda Equipación 2025',             liga:'selecciones', categoria:['selecciones'],        imgs:${makeImgs(41)}, tipo:'regular', badge:null },
    { id:42, nombre:'Portugal Segunda Equipación 2025',              liga:'selecciones', categoria:['selecciones'],        imgs:${makeImgs(42)}, tipo:'regular', badge:null },
    { id:43, nombre:'Portugal Prepartido 2025',                      liga:'selecciones', categoria:['selecciones'],        imgs:${makeImgs(43)}, tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · SAUDI PRO LEAGUE ──
    { id:44, nombre:'Al Hilal Tercera Equipación 25/26',             liga:'saudi',       categoria:['saudi'],              imgs:${makeImgs(44)}, tipo:'regular', badge:null },
    { id:45, nombre:'Al Nassr Segunda Equipación 25/26',             liga:'saudi',       categoria:['saudi'],              imgs:${makeImgs(45)}, tipo:'regular', badge:null },
    { id:46, nombre:'Al Ittihad Segunda Equipación 25/26',           liga:'saudi',       categoria:['saudi'],              imgs:${makeImgs(46)}, tipo:'regular', badge:null },
    // ── TEMPORADA 25/26 · OTROS ──
    { id:47, nombre:'Flamengo Tercera Equipación 25/26',             liga:'otros',       categoria:['otros'],              imgs:${makeImgs(47)}, tipo:'regular', badge:null },
    // ════════════════════════════════════════════════════════
    // ── RETRO ──
    // ════════════════════════════════════════════════════════
    { id:101, nombre:'Real Madrid 02/03 Primera Equipación',                 liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(101)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:102, nombre:'Rayo Vallecano 01/02 Primera Equipación',              liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(102)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:103, nombre:'PSV 94/95 Primera Equipación',                         liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(103)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:104, nombre:'Portugal 2004 Segunda Equipación',                     liga:'retro', categoria:['retro','selecciones'], imgs:${makeImgs(104)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:105, nombre:'Países Bajos 2014 Primera Equipación',                 liga:'retro', categoria:['retro','selecciones'], imgs:${makeImgs(105)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:106, nombre:'Oviedo 96/97 Primera Equipación',                      liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(106)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:107, nombre:'Osasuna 95/97 Primera Equipación',                     liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(107)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:108, nombre:'AC Milan 125 Aniversario Primera Equipación',          liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(108)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:109, nombre:'Inter Milan 94/95 Segunda Equipación',                 liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(109)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:110, nombre:'AC Milan 99/00 Segunda Equipación',                    liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(110)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:111, nombre:'Manchester United 98/99 Tercera Equipación',           liga:'retro', categoria:['retro','premier'],     imgs:${makeImgs(111)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:112, nombre:'Manchester United 03/05 Segunda Equipación',           liga:'retro', categoria:['retro','premier'],     imgs:${makeImgs(112)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:113, nombre:'Manchester City 13/14 Segunda Equipación',             liga:'retro', categoria:['retro','premier'],     imgs:${makeImgs(113)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:114, nombre:'Málaga 12/13 Segunda Equipación',                      liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(114)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:115, nombre:'Málaga 05/06 Primera Equipación',                      liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(115)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:116, nombre:'Lyon 10/11 Primera Equipación',                        liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(116)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:117, nombre:'Inter de Milán 04/05 Primera Equipación',              liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(117)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:118, nombre:'Inter de Milán 95/96 Primera Equipación',              liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(118)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:119, nombre:'Inter de Milán 02/03 Primera Equipación',              liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(119)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:120, nombre:'Granada 97/98 Primera Equipación',                     liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(120)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:121, nombre:'Getafe 98/99 Primera Equipación',                      liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(121)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:122, nombre:'Francia 2006 Segunda Equipación',                      liga:'retro', categoria:['retro','selecciones'], imgs:${makeImgs(122)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:123, nombre:'Fiorentina 95/96 Tercera Equipación',                  liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(123)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:124, nombre:'FC Barcelona 2002 Segunda Equipación',                 liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(124)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:125, nombre:'FC Barcelona 98/99 Tercera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(125)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:126, nombre:'FC Barcelona 13/14 Tercera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(126)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:127, nombre:'FC Barcelona 82/84 Segunda Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(127)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:128, nombre:'FC Barcelona 07/08 Segunda Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(128)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:129, nombre:'FC Barcelona 03/04 Segunda Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(129)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:130, nombre:'FC Barcelona 96/97 Primera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(130)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:131, nombre:'FC Barcelona 91/92 Primera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(131)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:132, nombre:'FC Barcelona 09/10 Primera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(132)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:133, nombre:'FC Barcelona 08/09 Final Champions',                   liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(133)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:134, nombre:'FC Barcelona 05/06 Primera Equipación',                liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(134)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:135, nombre:'España 2000 Segunda Equipación',                       liga:'retro', categoria:['retro','selecciones'], imgs:${makeImgs(135)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:136, nombre:'España 2000 Primera Equipación',                       liga:'retro', categoria:['retro','selecciones'], imgs:${makeImgs(136)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:137, nombre:'Deportivo De La Coruña 99/00 Segunda Equipación',      liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(137)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:138, nombre:'Deportivo De La Coruña 97/98 Primera Equipación',      liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(138)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:139, nombre:'Celta de Vigo 99/00 Primera Equipación',               liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(139)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:140, nombre:'Cádiz 83/84 Primera Equipación',                       liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(140)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:141, nombre:'Brasil 2004 Primera Equipación',                       liga:'retro', categoria:['retro','selecciones'], imgs:${makeImgs(141)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:142, nombre:'Boca Juniors 06/07 Primera Equipación',                liga:'retro', categoria:['retro'],               imgs:${makeImgs(142)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:143, nombre:'Betis 1993 Primera Equipación',                        liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(143)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:144, nombre:'Betis 88/89 Primera Equipación',                       liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(144)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:145, nombre:'Betis 95/96 Primera Equipación',                       liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(145)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:146, nombre:'Benfica 97/99 Segunda Equipación',                     liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(146)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:147, nombre:'Bayern München 14/15 Primera Equipación',              liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(147)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:148, nombre:'Bayern München 07/08 Primera Equipación',              liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(148)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:149, nombre:'Bayern München 05/06 Primera Equipación',              liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(149)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:150, nombre:'Bayern München 01/02 Primera Equipación',              liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(150)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:151, nombre:'Bayern München 00/01 Primera Equipación',              liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(151)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:152, nombre:'Bayer Leverkusen 01/02 Primera Equipación',            liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(152)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:153, nombre:'Atlético de Madrid 97/98 Segunda Equipación',          liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(153)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:154, nombre:'Atlético de Madrid 96/97 Segunda Equipación',          liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(154)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:155, nombre:'Atlético de Madrid 99/00 Primera Equipación',          liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(155)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:156, nombre:'Atlético de Madrid 98/99 Primera Equipación',          liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(156)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:157, nombre:'Atlético de Madrid 12/13 Primera Equipación',          liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(157)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:158, nombre:'Atlético de Madrid 04/05 Primera Equipación M/L',      liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(158)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:159, nombre:'Athletic Club Bilbao Edición Centenario',              liga:'retro', categoria:['retro','laliga'],      imgs:${makeImgs(159)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:160, nombre:'AS Roma 92/94 Tercera Equipación',                     liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(160)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:161, nombre:'AS Roma 91/92 Tercera Equipación',                     liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(161)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:162, nombre:'AS Roma 92/94 Segunda Equipación',                     liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(162)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:163, nombre:'AS Roma 99/00 Primera Equipación',                     liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(163)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:164, nombre:'Arsenal 94/95 Segunda Equipación',                     liga:'retro', categoria:['retro','premier'],     imgs:${makeImgs(164)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:165, nombre:'Arsenal 93/94 Segunda Equipación',                     liga:'retro', categoria:['retro','premier'],     imgs:${makeImgs(165)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:166, nombre:'Arsenal 02/04 Primera Equipación M/L',                 liga:'retro', categoria:['retro','premier'],     imgs:${makeImgs(166)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:167, nombre:'Alemania 1986 Primera Equipación',                     liga:'retro', categoria:['retro','selecciones'], imgs:${makeImgs(167)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:168, nombre:'Alemania 02/03 Primera Equipación',                    liga:'retro', categoria:['retro','selecciones'], imgs:${makeImgs(168)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
    { id:169, nombre:'AC Milan 03/04 Primera Equipación',                    liga:'retro', categoria:['retro','champions'],   imgs:${makeImgs(169)},  tipo:'retro', badge:'retro', badgeTexto:'Retro' },
  ];`;

fs.writeFileSync('C:/Users/tonim/KitZone/new_camisetas.txt', CAMISETAS_JS);
console.log('Done! Lines:', CAMISETAS_JS.split('\n').length);
console.log('Sample id:1:', makeImgs(1));
console.log('Sample id:101:', makeImgs(101));
console.log('Sample id:113 (ManCity - was duplicate):', makeImgs(113));
